### ISSUE TITLE
Deserialization failure on old events 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1025]
In #1003 we have removed the field `isNotifiedForInvoices`, so if we try to access existing notifications where this field is present we encounter a deserialization error.

**Example of data:**

```
|      8632 | org.killbill.billing.account.api.user.DefaultAccountCreationEvent | {"data":{"externalKey":"0232811865","name":"Louna Huet","firstNameLength":5,"email":"la.bertrand@vaeur.org","billCycleDayLocal":0,"currency":"EUR","paymentMethodId":null,"timeZone":"America/Chihuahua","locale":"fr","address1":"4981 Place des Francs-Bourgeois","address2":"Apt. 174","companyName":"Paris et Lemoine: Extended empowering help-desk","city":"Dunkerque14","stateOrProvince":"Picardie","postalCode":"25848","country":"MU","phone":"+33 372198446","isMigrated":null,"isNotifiedForInvoices":false},"id":"3c9996bb-acc1-4ead-84b8-54ab3b9ea7f8","searchKey1":1675,"searchKey2":1,"userToken":"5fbfdaa8-fd6c-47ed-ae32-028d69944433"} | 5fbfdaa8-fd6c-47ed-ae32-028d69944433 | 2015-01-02 08:00:43 | 802b3d21d3a1   | 802b3d21d3a1     | 2015-01-02 08:00:43       | PROCESSED        |           0 |        1675 |           1 |
```

**Example of error:**
```
2018-07-19T20:31:48,357+0000 lvl='ERROR', log='CallableCallbackBase', th='catalina-exec-101', xff='', rId='43cea031-e503-4956-a627-129ef50d552e', tok='', aRId='', tRId='1', Failed to deserialize json object {"data":{"externalKey":"0232811865","name":************,"firstNameLength":5,"email":***********************,"billCycleDayLocal":0,"currency":"EUR","paymentMethodId":null,"timeZone":"America/Chihuahua","locale":"fr","address1":"4981 Place des Francs-Bourgeois","address2":"Apt. 174","companyName":*************************************************,"city":"Dunkerque14","stateOrProvince":"Picardie","postalCode":"25848","country":"MU","phone":"+33 372198446","isMigrated":null,"isNotifiedForInvoices":false},"id":"3c9996bb-acc1-4ead-84b8-54ab3b9ea7f8","searchKey1":1675,"searchKey2":1,"userToken":"5fbfdaa8-fd6c-47ed-ae32-028d69944433"} for class org.killbill.billing.account.api.user.DefaultAccountCreationEvent
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isNotifiedForInvoices" (class org.killbill.billing.account.api.user.DefaultAccountCreationEvent$DefaultAccountData), not marked as ignorable (22 known properties: "firstNameLength", "paymentMethodId", "isMigrated", "stateOrProvince", "isPaymentDelegatedToParent", "name", "billCycleDayLocal", "currency", "externalKey", "country", "referenceTime", "timeZone", "locale", "email", "address1", "parentAccountId", "notes", "companyName", "city", "phone", "postalCode", "address2"])
 at [Source: {"data":{"externalKey":"0232811865","name":"Louna Huet","firstNameLength":5,"email":"la.bertrand@vaeur.org","billCycleDayLocal":0,"currency":"EUR","paymentMethodId":null,"timeZone":"America/Chihuahua","locale":"fr","address1":"4981 Place des Francs-Bourgeois","address2":"Apt. 174","companyName":"Paris et Lemoine: Extended empowering help-desk","city":"Dunkerque14","stateOrProvince":"Picardie","postalCode":"25848","country":"MU","phone":"+33 372198446","isMigrated":null,"isNotifiedForInvoices":false},"id":"3c9996bb-acc1-4ead-84b8-54ab3b9ea7f8","searchKey1":1675,"searchKey2":1,"userToken":"5fbfdaa8-fd6c-47ed-ae32-028d69944433"}; line: 1, column: 505] (through reference chain: org.killbill.billing.account.api.user.DefaultAccountCreationEvent["data"]->org.killbill.billing.account.api.user.DefaultAccountData["isNotifiedForInvoices"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1306)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:453)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at org.killbill.queue.dispatching.CallableCallbackBase.deserializeEvent(CallableCallbackBase.java:57)
	at org.killbill.bus.DefaultPersistentBus.toBusEventWithMetadata(DefaultPersistentBus.java:419)
	at org.killbill.bus.DefaultPersistentBus.access$400(DefaultPersistentBus.java:71)
	at org.killbill.bus.DefaultPersistentBus$10.apply(DefaultPersistentBus.java:413)
	at org.killbill.bus.DefaultPersistentBus$10.apply(DefaultPersistentBus.java:410)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.MultitransformedIterator.next(MultitransformedIterator.java:66)
	at org.killbill.billing.jaxrs.resources.AdminResource$1.write(AdminResource.java:194)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

```

**Comment by sbrossie** [comment]
Note that this error is also seen on the UI when fetching queue entry (with old history), and shows up as a `Error: incompatible encodings: ASCII-8BIT and UTF-8` error.

**Comment by sbrossie** [comment]
@pierre I think configuring jackson to ignore unknown fields -- something that was suggesting several times to us in the past would be a good move ?

**Comment by pierre** [comment]
Yup, agreed. 👍

**Comment by sbrossie** [comment]
@pierre See following PRs - we have at least 3 instances of ObjectMapper that need to be configured:
* `common` : Used for the queue : See  https://github.com/killbill/killbill-commons/pull/52/
* `platform`: Used to configure jersey object mapper: See https://github.com/killbill/killbill-platform/pull/37
* `killbill`: Used inside KB: See https://github.com/killbill/killbill/pull/1026
