### ISSUE TITLE
IllegalStateException in dry-run generation

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1095]
Scenario: trigger dry run invoice generation with a target date that is after the subscription (in-arrear usage) cancellation date.

```
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at org.killbill.billing.invoice.usage.RawUsageOptimizer.getOptimizedRawUsageStartDate(RawUsageOptimizer.java:124)
	at org.killbill.billing.invoice.usage.RawUsageOptimizer.getInArrearUsage(RawUsageOptimizer.java:75)
	at org.killbill.billing.invoice.generator.UsageInvoiceItemGenerator.generateItems(UsageInvoiceItemGenerator.java:117)
	at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:98)
	at org.killbill.billing.invoice.InvoiceDispatcher.generateKillBillInvoice(InvoiceDispatcher.java:667)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:556)
	at org.killbill.billing.invoice.InvoiceDispatcher.processDryRun_TARGET_DATE_Invoice(InvoiceDispatcher.java:490)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:390)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:306)
```

**Comment by pierre** [comment]
Not reproducible.
