### ISSUE TITLE
Ruby Plugins Unable to start in Windows

### ISSUE THREAD

**Issue by kbhuvanamohan** [killbill/killbill#1248]
Team -

It appears that when running ruby plugins from the Windows, the platform OSGI bundles are trying to **activate and load** the jruby.jar from the "C:/var/tmp/bundles/platform/jruby.jar" location.

Ideally it should be simply used to bootstrap the other ruby plugins we have, such as killbill-stripe and killbill-helloworld.

However, killbill is trying to load the jruby.jar file itself, which I believe could be because there appears to be a logic to **skip loading** only if it is "/var/tmp/bundles/platform/jruby.jar". As per the below comment:
https://github.com/killbill/killbill/issues/217#issuecomment-50375207

Please guide me how to overcome this or override the platform/jruby.jar location using some properties.

Thanks!

Here are the logs:

2019-12-09T14:16:50,814+0000 lvl='INFO', log='FileInstall', th='localhost-startStop-1', xff='', rId='', tok='', aRId='', tRId='', **Starting bundle file:C:\var\tmp\bundles\platform\jruby.jar**
OSGI bundle='org.kill-bill.billing.killbill-platform-osgi-bundles-jruby' received START command
2019-12-09T14:16:50,871+0000 lvl='WARN', log='FileInstall', th='localhost-startStop-1', xff='', rId='', tok='', aRId='', tRId='', Unable to start bundle
org.osgi.framework.BundleException: Activator start error in bundle org.kill-bill.billing.killbill-platform-osgi-bundles-jruby [1].
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2204)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.killbill.billing.osgi.FileInstall.startBundle(FileInstall.java:258)
        at org.killbill.billing.osgi.BundleRegistry.startBundles(BundleRegistry.java:103)
        at org.killbill.billing.osgi.DefaultOSGIService.start(DefaultOSGIService.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.killbill.billing.lifecycle.DefaultLifecycle.doFireStage(DefaultLifecycle.java:156)
        at org.killbill.billing.lifecycle.DefaultLifecycle.fireSequence(DefaultLifecycle.java:143)
        at org.killbill.billing.lifecycle.DefaultLifecycle.fireStartupSequencePriorEventRegistration(DefaultLifecycle.java:84)
        at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.startLifecycle(KillbillPlatformGuiceListener.java:307)
        at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.contextInitialized(KillbillPlatformGuiceListener.java:129)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.killbill.billing.osgi.libs.killbill.KillbillActivatorBase.setupTmpDir(KillbillActivatorBase.java:256)
        at org.killbill.billing.osgi.libs.killbill.KillbillActivatorBase.start(KillbillActivatorBase.java:78)
        at org.killbill.billing.osgi.bundles.jruby.JRubyActivator.start(JRubyActivator.java:58)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2154)
        ... 28 common frames omitted

**Comment by pierre** [comment]
@kbhuvanamohan The core team doesn't have a Windows environment to test Kill Bill on unfortunately, so it is supported as "best effort" only. We'd also be happy to integrate (reasonable) patches if you find ways to better support the platform.

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
