### ISSUE TITLE
ClassCastException in invoicing code

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1306]
Issue reported when doing a dry-run operation:

```
2020-06-01T17:45:05,171+0000 lvl='ERROR', log='LoggingResponse', th='catalina-exec-3', xff='', rId='4a326fdf-3a90-496a-b11f-95e1d2e527f2', tok='4a326fdf-3a90-496a-b11f-95e1d2e527f2', aRId='15337', tRId='1', org.killbill.billing.invoice.model.InvoiceItemCatalogBase cannot be cast to org.killbill.billing.invoice.model.RecurringInvoiceItem
java.lang.ClassCastException: org.killbill.billing.invoice.model.InvoiceItemCatalogBase cannot be cast to org.killbill.billing.invoice.model.RecurringInvoiceItem
    at org.killbill.billing.invoice.generator.InvoicePruner$AdjustedRecurringItem.addInvoiceItem(InvoicePruner.java:116)
    at org.killbill.billing.invoice.generator.InvoicePruner.<init>(InvoicePruner.java:80)
    at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.generateItems(FixedAndRecurringInvoiceItemGenerator.java:96)
    at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:99)
    at org.killbill.billing.invoice.InvoiceDispatcher.generateKillBillInvoice(InvoiceDispatcher.java:673)
    at ```

**Comment by sbrossie** [comment]
See #1095 also.

**Comment by sbrossie** [comment]
It looks like our code makes [assumptions](https://github.com/killbill/killbill/blob/killbill-0.22.8/invoice/src/main/java/org/killbill/billing/invoice/generator/InvoicePruner.java#L116) around `InvoiceItem` type and specific implementation.  

However, looking in the code I can find a couple of examples where such assumptions are being violated:
* When creating invoice items from given from invoice plugin [here](https://github.com/killbill/killbill/blob/killbill-0.22.8/invoice/src/main/java/org/killbill/billing/invoice/InvoicePluginDispatcher.java#L231).
* In the path when creating adj [here]: `https://github.com/killbill/killbill/blob/killbill-0.22.8/invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java#L192`

Not sure if this list is exhaustive, but we have to decide what the assumption should be:
1. Either ensure that all items of a certain type map to a specific class implementation
2. Or, if this not true, prevent any of these type of cast throughout our code.
