### ISSUE TITLE
Dry-run throws exception when using AUTO_INVOICING_REUSE_DRAFT

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1313]
The following stack trace is being thrown:

```
java.lang.IllegalStateException: Unexpected second recurring item with ID 12f17a48-0cc7-4959-b22a-a7c657a06d21
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at org.killbill.billing.invoice.generator.InvoicePruner$AdjustedRecurringItem.setTargetItem(InvoicePruner.java:133)
	at org.killbill.billing.invoice.generator.InvoicePruner$AdjustedRecurringItem.addInvoiceItem(InvoicePruner.java:115)
	at org.killbill.billing.invoice.generator.InvoicePruner.<init>(InvoicePruner.java:79)
	at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.generateItems(FixedAndRecurringInvoiceItemGenerator.java:96)
	at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:99)
	at org.killbill.billing.invoice.InvoiceDispatcher.generateKillBillInvoice(InvoiceDispatcher.java:673)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:557)
	at org.killbill.billing.invoice.InvoiceDispatcher.processDryRun_TARGET_DATE_Invoice(InvoiceDispatcher.java:479)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:391)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:307)
```

**Comment by sbrossie** [comment]
The main issue is that when doing dry-run operation the code maintains a list of `augmentedExistingInvoices` to keep track of what is being generated at each date boundary, and  so when combining with `AUTO_INVOICING_REUSE_DRAFT` , this list maps to multiple Invoice java object, each of which with the same invoiceId (the one being reused) and the items keep being repeated at each round.
