### ISSUE TITLE
Internal DAO logic to return correct exception duplicate key is flawed

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1344]
While creating multiple accounts with the same external key in parallel, we sometimes get the following exception:

```
2020-08-20T00:42:18,429+0000 lvl='WARN', log='EntitySqlDaoWrapperInvocationHandler', th='qtp237503491-86', xff='', rId='30d0682c-8533-4f99-bc23-7fc85f41c432', tok='30d0682c-8533-4f99-bc23-7fc85f41c432', aRId='', tRId='10', Error during transaction for sql entity interface org.killbill.billing.account.dao.AccountSqlDao and method create [SQL DefaultState: 23000, Vendor Error Code: 1062]
com.zaxxer.hikari.proxy.HikariPreparedStatementProxy@1dc5e930
{ positional:{}, named:{billingCycleDayLocal:1,country:'null',firstNameLength:null,notes:'null',city:'null',contextUserType:CUSTOMER,companyName:'null',postalCode:'null',updatedDate:DateTimeArgument{value=2020-08-20T00:42:18.000Z},locale:'en_US',tableName:ACCOUNT,parentAccountId:UUIDArgument{value=null},recordId:null,externalKey:'ebd5dff9-49c9-4c66-921e-19b01bc3da9d',referenceTime:DateTimeArgument{value=2020-08-20T00:42:18.202Z},paymentMethodId:UUIDArgument{value=null},currency:USD,id:UUIDArgument{value=30912dbb-36aa-4669-bcb8-379c6305aed6},reasonCode:'null',migrated:null,class:class org.killbill.billing.callcontext.InternalCallContext,email:'null',callOrigin:EXTERNAL,tenantRecordId:10,comments:'null',updatedBy:'foo',address2:'null',address1:'null',timeZone:DateTimeZoneArgument{value=UTC},fixedOffsetTimeZone:DateTimeZoneArgument{value=null},accountRecordId:null,userToken:UUIDArgument{value=30d0682c-8533-4f99-bc23-7fc85f41c432},createdDate:DateTimeArgument{value=2020-08-20T00:42:18.000Z},stateOrProvince:'null',isPaymentDelegatedToParent:null,phone:'null',createdBy:'foo',referenceLocalTime:null,name:'null',historyTableName:ACCOUNT_HISTORY}, finder:[]}
2020-08-20T00:42:18,442+0000 lvl='INFO', log='BeatrixListener', th='bus_events-th', xff='', rId='', tok='9b60f4e7-6d3d-47d7-a146-414bf08f0cc9', aRId='201', tRId='10', Sending extBusEvent='DefaultBusExternalEvent{objectId=98960d10-aada-4745-a453-0f1e44466542, accountId=98960d10-aada-4745-a453-0f1e44466542, tenantId=294b6ea5-2f73-4e45-b1cf-ab4fdd1a3f48, objectType=ACCOUNT, eventType=ACCOUNT_CREATION}' from busEvent='DefaultAccountCreationEvent{id=98960d10-aada-4745-a453-0f1e44466542, data=org.killbill.billing.account.api.user.DefaultAccountCreationEvent$DefaultAccountData@4864a219}'
2020-08-20T00:42:18,445+0000 lvl='WARN', log='LoggingResponse', th='qtp237503491-86', xff='', rId='30d0682c-8533-4f99-bc23-7fc85f41c432', tok='30d0682c-8533-4f99-bc23-7fc85f41c432', aRId='', tRId='10', Internal error
java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: (conn=50) Duplicate entry 'ebd5dff9-49c9-4c66-921e-19b01bc3da9d-10' for key 'accounts.accounts_external_key'
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.errorDuringTransaction(EntitySqlDaoWrapperInvocationHandler.java:175)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invoke(EntitySqlDaoWrapperInvocationHandler.java:133)
	at com.sun.proxy.$Proxy223.create(Unknown Source)
	at org.killbill.billing.util.entity.dao.EntityDaoBase.createAndRefresh(EntityDaoBase.java:130)
	at org.killbill.billing.util.entity.dao.EntityDaoBase$1.inTransaction(EntityDaoBase.java:107)
	at org.killbill.billing.util.entity.dao.EntityDaoBase$1.inTransaction(EntityDaoBase.java:97)
	at org.killbill.billing.util.entity.dao.EntityDaoBase$2.inTransaction(EntityDaoBase.java:122)
	at org.killbill.billing.util.entity.dao.EntityDaoBase$2.inTransaction(EntityDaoBase.java:119)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:74)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:61)
	at org.skife.jdbi.v2.sqlobject.InTransactionHandler$1.inTransaction(InTransactionHandler.java:37)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:82)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:60)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:328)
	at org.skife.jdbi.v2.sqlobject.InTransactionHandler.invoke(InTransactionHandler.java:32)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:180)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:93)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$698fbb7d.inTransaction(<generated>)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:98)
	at org.killbill.billing.account.dao.DefaultAccountDao.create(DefaultAccountDao.java:102)
	at org.killbill.billing.account.dao.DefaultAccountDao.create(DefaultAccountDao.java:71)
	at org.killbill.billing.account.api.user.DefaultAccountUserApi.createAccount(DefaultAccountUserApi.java:110)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.AccountResource.createAccount(AccountResource.java:369)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69)
	at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor$1.execute(JaxRSAopModule.java:87)
	at org.killbill.billing.util.entity.dao.DBRouterUntyped.withRODBIAllowed(DBRouterUntyped.java:57)
	at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor.invoke(JaxRSAopModule.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:111)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=50) Duplicate entry 'ebd5dff9-49c9-4c66-921e-19b01bc3da9d-10' for key 'accounts.accounts_external_key'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:171)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
	at org.mariadb.jdbc.MariaDbPreparedStatementServer.executeInternal(MariaDbPreparedStatementServer.java:381)
	at org.mariadb.jdbc.MariaDbPreparedStatementServer.execute(MariaDbPreparedStatementServer.java:343)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1330)
	at org.skife.jdbi.v2.Update.executeAndReturnGeneratedKeys(Update.java:79)
	at org.skife.jdbi.v2.sqlobject.UpdateHandler$2.value(UpdateHandler.java:61)
	at org.skife.jdbi.v2.sqlobject.UpdateHandler.invoke(UpdateHandler.java:86)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:180)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:93)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$7433d727.create(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.executeJDBCCall(EntitySqlDaoWrapperInvocationHandler.java:311)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.access$100(EntitySqlDaoWrapperInvocationHandler.java:80)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$3.execute(EntitySqlDaoWrapperInvocationHandler.java:232)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeWithAuditAndHistory(EntitySqlDaoWrapperInvocationHandler.java:229)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeSafely(EntitySqlDaoWrapperInvocationHandler.java:193)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.access$000(EntitySqlDaoWrapperInvocationHandler.java:80)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$1.execute(EntitySqlDaoWrapperInvocationHandler.java:117)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invoke(EntitySqlDaoWrapperInvocationHandler.java:114)
	... 99 common frames omitted
Caused by: java.sql.SQLException: Duplicate entry 'ebd5dff9-49c9-4c66-921e-19b01bc3da9d-10' for key 'accounts.accounts_external_key'
Query is: insert into accounts (
  id
, external_key
, email
, name
, first_name_length
, currency
, billing_cycle_day_local
, parent_account_id
, is_payment_delegated_to_parent
, payment_method_id
, reference_time
, time_zone
, locale
, address1
, address2
, company_name
, city
, state_or_province
, country
, postal_code
, phone
, notes
, migrated
, created_by
, created_date
, updated_by
, updated_date
, tenant_record_id
)
values (
  ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
, ?
), parameters ['30912dbb-36aa-4669-bcb8-379c6305aed6','ebd5dff9-49c9-4c66-921e-19b01bc3da9d',<null>,<null>,<null>,'USD',1,<null>,<null>,<null>,'2020-08-20 00:42:18.202','UTC','en_US',<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,'foo','2020-08-20 00:42:18.0','foo','2020-08-20 00:42:18.0',10]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:971)
	at org.mariadb.jdbc.MariaDbPreparedStatementServer.executeInternal(MariaDbPreparedStatementServer.java:375)
	... 123 common frames omitted
2020-08-20T00:42:18,446+0000 lvl='INFO', log='LoggingFilter', th='qtp237503491-86', xff='', rId='30d0682c-8533-4f99-bc23-7fc85f41c432', tok='30d0682c-8533-4f99-bc23-7fc85f41c432', aRId='', tRId='10', 4 * Server out-bound response
4 < 500
4 < Content-Type: application/json
4 < 
```

Notes: We also sometimes get the correct error (based on timing) :

```
2020-08-20T00:50:20,891+0000 lvl='INFO', log='BeatrixListener', th='bus_events-th', xff='', rId='', tok='c44334d2-378d-4a3f-ab3c-768fdc485a8f', aRId='204', tRId='10', Sending extBusEvent='DefaultBusExternalEvent{objectId=b73d3c4b-bc7f-4a25-a649-665eb7dbbc71, accountId=b73d3c4b-bc7f-4a25-a649-665eb7dbbc71, tenantId=294b6ea5-2f73-4e45-b1cf-ab4fdd1a3f48, objectType=ACCOUNT, eventType=ACCOUNT_CREATION}' from busEvent='DefaultAccountCreationEvent{id=b73d3c4b-bc7f-4a25-a649-665eb7dbbc71, data=org.killbill.billing.account.api.user.DefaultAccountCreationEvent$DefaultAccountData@2b843994}'
2020-08-20T00:50:20,913+0000 lvl='INFO', log='LoggingFilter', th='qtp237503491-83', xff='', rId='a65bc047-6701-432f-8b82-8fc488909673', tok='', aRId='', tRId='10', 31 * Server in-bound request
31 > POST http://127.0.0.1:8080/1.0/kb/accounts
31 > Authorization: **************************
31 > X-Killbill-Apikey: embs-test
31 > Accept: application/json
31 > X-Killbill-Apisecret: ***********
31 > User-Agent: Go-http-client/1.1
31 > Host: 127.0.0.1:8080
31 > Accept-Encoding: gzip
31 > Content-Length: 176
31 > X-Killbill-Createdby: embs
31 > Content-Type: application/json
31 > 

2020-08-20T00:50:20,916+0000 lvl='WARN', log='LoggingResponse', th='qtp237503491-83', xff='', rId='a65bc047-6701-432f-8b82-8fc488909673', tok='a65bc047-6701-432f-8b82-8fc488909673', aRId='', tRId='10', Conflicting request
org.killbill.billing.account.api.AccountApiException: Account already exists for key f3851ef8-da7e-491e-bbd3-2bcee386c40e
	at org.killbill.billing.account.api.user.DefaultAccountUserApi.createAccount(DefaultAccountUserApi.java:92)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.AccountResource.createAccount(AccountResource.java:369)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69)
...
```

This behavior is probably the same for all our resources as we share the same internal mechanics

**Comment by sbrossie** [comment]
Investigating more the issue shows at least 3 problems:

1. The [api check](https://github.com/killbill/killbill/blob/killbill-0.22.11/account/src/main/java/org/killbill/billing/account/api/user/DefaultAccountUserApi.java#L92) will not solve concurrent request that will both try to create the account in parallel transactions. When lucky, it does provide the correct behavior though.
2. We have some [in-transaction logic](https://github.com/killbill/killbill/blob/killbill-0.22.11/util/src/main/java/org/killbill/billing/util/entity/dao/EntityDaoBase.java#L105) to check that we don't try to insert twice the same object. However [this logic](https://github.com/killbill/killbill/blob/killbill-0.22.11/util/src/main/java/org/killbill/billing/util/entity/dao/EntityDaoBase.java#L148) is based on the `ID` of the incoming object, which randomly allocated for each parallel request and therefore does not catch the issue -> we would need to check for the external key instead.
3. Adding some logic inside `EntityDaoBase#getCreateEntitySqlDaoTransactionWrapper` to catch the `java.sql.SQLIntegrityConstraintViolationException` and transform it into the right exception by calling the abstract `generateAlreadyExistsException` does not work because jdbi wraps it into a `TransactionFailedException` and then the `RestartTransactionRunner` which [re-throws a RuntimeException](https://github.com/killbill/killbill-commons/blob/killbill-commons-0.23.11/jdbi/src/main/java/org/killbill/commons/jdbi/transaction/RestartTransactionRunner.java#L64).
