### ISSUE TITLE
Guice injection issue

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1408]
Based on some recent code changes, it seems that we have a latent issue with our overall injection. The exception thrown is a `java.lang.ClassCastException` (and not something related to some missing bindings or circular dependencies).

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.ClassCastException: com.sun.proxy.$Proxy86 cannot be cast to javax.inject.Provider
  at org.killbill.billing.util.glue.CacheModule.configure(CacheModule.java:72) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.util.glue.CacheModule)
  while locating javax.cache.CacheManager
    for the 1st parameter of org.killbill.billing.util.cache.CacheControllerDispatcherProvider.<init>(CacheControllerDispatcherProvider.java:46)
  while locating org.killbill.billing.util.cache.CacheControllerDispatcherProvider
  at org.killbill.billing.util.glue.CacheModule.configure(CacheModule.java:76) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.util.glue.CacheModule)
  while locating org.killbill.billing.util.cache.CacheControllerDispatcher
    for the 1st parameter of org.killbill.billing.util.config.tenant.CacheConfig.<init>(CacheConfig.java:43)
  at org.killbill.billing.util.glue.ConfigModule.configure(ConfigModule.java:42) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.util.glue.ConfigModule)
  while locating org.killbill.billing.util.config.tenant.CacheConfig
    for the 2nd parameter of org.killbill.billing.util.config.definition.MultiTenantEventConfig.<init>(MultiTenantEventConfig.java:37)
  while locating org.killbill.billing.util.config.definition.MultiTenantEventConfig
  at org.killbill.billing.util.glue.ConfigModule.configure(ConfigModule.java:48) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.util.glue.ConfigModule)
  while locating org.killbill.billing.util.config.definition.EventConfig
    for the 2nd parameter of org.killbill.billing.util.optimizer.BusOptimizerOn.<init>(BusOptimizerOn.java:48)
  while locating org.killbill.billing.util.optimizer.BusOptimizerOn
  at org.killbill.billing.server.modules.KillbillServerModule.configureBuses(KillbillServerModule.java:112)
  while locating org.killbill.billing.util.optimizer.BusOptimizer
    for the 3rd parameter of org.killbill.billing.tenant.api.TenantCacheInvalidation.<init>(TenantCacheInvalidation.java:84)
  at org.killbill.billing.tenant.glue.DefaultTenantModule.installTenantCacheInvalidation(DefaultTenantModule.java:78) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.tenant.glue.DefaultTenantModule)
  while locating org.killbill.billing.tenant.api.TenantCacheInvalidation
    for the 2nd parameter of org.killbill.billing.tenant.api.DefaultTenantInternalApi.<init>(DefaultTenantInternalApi.java:53)
  while locating org.killbill.billing.tenant.api.DefaultTenantInternalApi
  at org.killbill.billing.tenant.glue.DefaultTenantModule.installTenantUserApi(DefaultTenantModule.java:69) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.tenant.glue.DefaultTenantModule)
  while locating org.killbill.billing.tenant.api.TenantInternalApi
    for the 1st parameter of org.killbill.billing.util.cache.TenantCatalogCacheLoader.<init>(TenantCatalogCacheLoader.java:42)
  at org.killbill.billing.util.cache.TenantCatalogCacheLoader.class(TenantCatalogCacheLoader.java:33)
  while locating org.killbill.billing.util.cache.TenantCatalogCacheLoader
  at org.killbill.billing.util.glue.CacheModule.configure(CacheModule.java:85) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.util.glue.CacheModule)
  while locating org.killbill.billing.util.cache.BaseCacheLoader annotated with @com.google.inject.internal.Element(setName=,uniqueId=121, type=MULTIBINDER, keyType=)
  while locating java.util.Set<org.killbill.billing.util.cache.BaseCacheLoader>
    for the 3rd parameter of org.killbill.billing.util.glue.Eh107CacheManagerProvider.<init>(Eh107CacheManagerProvider.java:50)
  while locating org.killbill.billing.util.glue.Eh107CacheManagerProvider
  at org.killbill.billing.util.glue.CacheModule.configure(CacheModule.java:72) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.util.glue.CacheModule)
  while locating javax.cache.CacheManager
    for the 3rd parameter of org.killbill.billing.util.glue.EhcacheShiroManagerProvider.<init>(EhcacheShiroManagerProvider.java:53)
  while locating org.killbill.billing.util.glue.EhcacheShiroManagerProvider
  at org.killbill.billing.server.modules.KillBillShiroWebModule.configureShiroWeb(KillBillShiroWebModule.java:96) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.server.modules.KillBillShiroWebModule)
  while locating org.apache.shiro.cache.CacheManager
  at org.apache.shiro.guice.ShiroModule.bindRealm(ShiroModule.java:105) (via modules: org.killbill.billing.server.modules.KillbillServerModule -> org.killbill.billing.server.modules.KillBillShiroWebModule)

1 error
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist (Errors.java:554)
    at com.google.inject.internal.InternalInjectorCreator.injectDynamically (InternalInjectorCreator.java:180)
    at com.google.inject.internal.InternalInjectorCreator.build (InternalInjectorCreator.java:111)
    at com.google.inject.Guice.createInjector (Guice.java:87)
    at org.killbill.commons.skeleton.listeners.GuiceServletContextListener.getInjector (GuiceServletContextListener.java:97)
    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized (GuiceServletContextListener.java:45)
    at org.killbill.commons.skeleton.listeners.GuiceServletContextListener.contextInitialized (GuiceServletContextListener.java:59)
    at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.initializeGuice (KillbillPlatformGuiceListener.java:185)
...
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy86 cannot be cast to javax.inject.Provider
    at com.google.inject.internal.BoundProviderFactory.get (BoundProviderFactory.java:60)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
    at com.google.inject.internal.SingletonScope$1.get (SingletonScope.java:168)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get (InternalFactoryToProviderAdapter.java:39)
    at com.google.inject.internal.SingleParameterInjector.inject (SingleParameterInjector.java:42)
    at com.google.inject.internal.SingleParameterInjector.getAll (SingleParameterInjector.java:65)
    at com.google.inject.internal.ConstructorInjector.provision (ConstructorInjector.java:113)
    at com.google.inject.internal.ConstructorInjector.construct (ConstructorInjector.java:91)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get (ConstructorBindingImpl.java:306)
    at com.google.inject.internal.BoundProviderFactory.get (BoundProviderFactory.java:60)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
    at com.google.inject.internal.SingletonScope$1.get (SingletonScope.java:168)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get (InternalFactoryToProviderAdapter.java:39)
    at com.google.inject.internal.SingleParameterInjector.inject (SingleParameterInjector.java:42)
    at com.google.inject.internal.SingleParameterInjector.getAll (SingleParameterInjector.java:65)
    at com.google.inject.internal.ConstructorInjector.provision (ConstructorInjector.java:113)
    at com.google.inject.internal.ConstructorInjector.construct (ConstructorInjector.java:91)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get (ConstructorBindingImpl.java:306)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
...
```

**Comment by sbrossie** [comment]
Debugging further the issue, the problem seems to arise with the injection of the `CacheManager`. 

To be precise, the exception arise for the class `org.killbill.billing.util.glue.Eh107CacheManagerProvider` but with a dependency `Key[type=javax.cache.CacheManager, annotation=[none]]@org.killbill.billing.util.cache.CacheControllerDispatcherProvider.<init>()[0]`.



Looking at the out bindings for `CacheManager`, we see 3 different bindings, all with the same key, i.e none have an annotation (e.g `@Named`):

- [CacheModule](https://github.com/killbill/killbill/blob/killbill-0.22.20/util/src/main/java/org/killbill/billing/util/glue/CacheModule.java#L72)
- [KillBillShiroModule](https://github.com/killbill/killbill/blob/killbill-0.22.20/util/src/main/java/org/killbill/billing/util/glue/KillBillShiroModule.java#L142)
- [KillBillShiroWebModule](https://github.com/killbill/killbill/blob/killbill-0.22.20/profiles/killbill/src/main/java/org/killbill/billing/server/modules/KillBillShiroWebModule.java#L96)

**Comment by sbrossie** [comment]
Details about the context of the exception:

<img width="2293" alt="Screen Shot 2021-03-03 at 2 20 24 PM" src="https://user-images.githubusercontent.com/246910/109880318-a181ac00-7c2b-11eb-981e-8d580057ef57.png">
