### ISSUE TITLE
NoSuchElementException when fetching subscriptions

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1415]
During a call to bulk subscription, we get a `NoSuchElementException` while trying to fetch the bundle:

```
java.util.NoSuchElementException: null
	at com.google.common.collect.Iterators.find(Iterators.java:697)
	at com.google.common.collect.Iterables.find(Iterables.java:631)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15$1.apply(DefaultSubscriptionDao.java:488)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15$1.apply(DefaultSubscriptionDao.java:485)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15.inTransaction(DefaultSubscriptionDao.java:485)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15.inTransaction(DefaultSubscriptionDao.java:478)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:74)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:61)
	at org.skife.jdbi.v2.sqlobject.InTransactionHandler$1.inTransaction(InTransactionHandler.java:41)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:188)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:86)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:62)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:332)
	at org.skife.jdbi.v2.sqlobject.InTransactionHandler.invoke(InTransactionHandler.java:36)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:184)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:97)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$93ec8c0.inTransaction(<generated>)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:98)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getSubscriptionsFromAccountId(DefaultSubscriptionDao.java:478)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getSubscriptionsForAccount(DefaultSubscriptionDao.java:451)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getSubscriptionsForAccount(DefaultSubscriptionInternalApi.java:291)
	at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForAccount(EventsStreamBuilder.java:143)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi.getAllEntitlementsForAccountId(DefaultEntitlementApi.java:246)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doResponseOk(SubscriptionResource.java:396)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doResponseOk(SubscriptionResource.java:359)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$EntitlementCallCompletion.withSynchronization(SubscriptionResource.java:836)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.createSubscriptionsWithAddOnsInternal(SubscriptionResource.java:415)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.createSubscriptionsWithAddOns(SubscriptionResource.java:285)
```

**Comment by sbrossie** [comment]
A relayed issue during load:

```
java.util.NoSuchElementException: null
    at com.google.common.collect.Iterators.find(Iterators.java:697)
    at com.google.common.collect.Iterables.find(Iterables.java:631)
    at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15$1.apply(DefaultSubscriptionDao.java:488)
    at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15$1.apply(DefaultSubscriptionDao.java:485)
    at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
    at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
    at java.util.ArrayList.<init>(ArrayList.java:178)
    at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15.inTransaction(DefaultSubscriptionDao.java:485)
    at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$15.inTransaction(DefaultSubscriptionDao.java:478)
    at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:74)
    at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:61)
    at org.skife.jdbi.v2.sqlobject.InTransactionHandler$1.inTransaction(InTransactionHandler.java:41)
    at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:188)
    at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:86)
    at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:62)
    at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:332)
    at org.skife.jdbi.v2.sqlobject.InTransactionHandler.invoke(InTransactionHandler.java:36)
    at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:184)
    at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:97)
    at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$93ec8c0.inTransaction(<generated>)
    at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:98)
    at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getSubscriptionsFromAccountId(DefaultSubscriptionDao.java:478)
    at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getSubscriptionsForAccount(DefaultSubscriptionDao.java:451)
    at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getSubscriptionsForAccount(DefaultSubscriptionInternalApi.java:291)
    at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForAccount(EventsStreamBuilder.java:143)
    at org.killbill.billing.entitlement.api.DefaultEntitlementApi.getAllEntitlementsForAccountId(DefaultEntitlementApi.java:246)
    at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
    at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
    at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
    at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doResponseOk(SubscriptionResource.java:396)
    at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doResponseOk(SubscriptionResource.java:359)
    at org.killbill.billing.jaxrs.resources.SubscriptionResource$EntitlementCallCompletion.withSynchronization(SubscriptionResource.java:836)
    at org.killbill.billing.jaxrs.resources.SubscriptionResource.createSubscriptionsWithAddOnsInternal(SubscriptionResource.java:415)
    at org.killbill.billing.jaxrs.resources.SubscriptionResource.createSubscriptionsWithAddOns(SubscriptionResource.java:285)
```
