### ISSUE TITLE
Voiding an invoice can lead to ILLEGAL INVOICING STATE

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1423]
Scenario:

* Invoice 1: recurring item1
* Invoice 2: `REPAIR_ADJ` against item1

After voiding invoice 1, `InvoicePruner` fails:

```
Caused by: java.lang.IllegalStateException: Missing cancelledItem for cancelItem=REPAIR_ADJ{startDate='2020-06-18', endDate='2020-07-18', amount='-10.00', linkedItemId='4ae72e64-b303-499d-95c3-594d9b307df8'}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
	at org.killbill.billing.invoice.generator.InvoicePruner$AdjustedRecurringItem.build(InvoicePruner.java:162)
	at org.killbill.billing.invoice.generator.InvoicePruner$AdjustedRecurringItem.getFullyRepairedLinkedItems(InvoicePruner.java:126)
	at org.killbill.billing.invoice.generator.InvoicePruner.getFullyRepairedItemsClosure(InvoicePruner.java:91)
```

`changeInvoiceStatus` needs to run additional checks to see if the transition is valid (could we invoke the tree builder in the DAO?).

**Comment by sbrossie** [comment]
I believe this should have been fixed in https://github.com/killbill/killbill/pull/1484/commits/fab2f33dd122164cf4f51c87c14c8ca1087ce2e6

/cc @pierre
