### ISSUE TITLE
Incorrect dry-run invoice returned when subscription is future cancelled

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1503]
Scenario: subscription billed monthly on the 1st, started on 2021-04-01 and cancelled on 2021-05-01.

When generating a dry-run invoice with a target date of 2021-05-01 (null invoice expected), Kill Bill returns the last non-null invoice (with a target date of 2021-04-01):

https://github.com/killbill/killbill/blob/454852dc9d09b5b636e7ae82517a9f4b1e5708f1/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L525

In 592e1e261a4640e2939888f00e9165db1a989b25, the code had the following comment:

```
// If our targetDate -- user specified -- did not align with any boundary, we return previous 'additionalInvoice' invoice
```

but it was removed in 1414a8b9268c4e84b815ac9435b8b5590b2b28eb.

The following diff:

```
diff --git a/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java b/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
index 1c5b66b07..e33ef2daf 100644
--- a/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
+++ b/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java
@@ -522,7 +522,7 @@ public class InvoiceDispatcher {
         pluginProperties.add(new PluginProperty(DRY_RUN_TARGET_DATE_PROP, targetDate, false));
         final InvoiceWithFutureNotifications invoiceWithFutureNotifications = processAccountWithLockAndInputTargetDate(accountId, targetDate, billingEvents, accountInvoices, dryRunInfo, false, pluginProperties, context);
         final Invoice targetInvoice = invoiceWithFutureNotifications != null ? invoiceWithFutureNotifications.getInvoice() : null;
-        return targetInvoice != null ? targetInvoice : additionalInvoice;
+        return targetInvoice;
     }

     private void parkAccount(final UUID accountId, final InternalCallContext context) {
```

makes the following test fail:

```
[ERROR] Tests run: 304, Failures: 1, Errors: 0, Skipped: 236, Time elapsed: 258.855 s <<< FAILURE! - in TestSuite
[ERROR] org.killbill.billing.beatrix.integration.TestIntegration.testBasePlanCompleteWithBillingDayInPast  Time elapsed: 2.937 s  <<< FAILURE!
{cause=null, code=4007, formattedMsg='No invoice to generate for account 6d036ada-a929-4f21-beef-a29a104c2930 and date 2012-04-02'}
	at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerDryRunInvoiceGeneration(DefaultInvoiceUserApi.java:274)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
	at org.killbill.billing.beatrix.integration.TestIntegration.testBasePlanCompleteWithBillingDayInPast(TestIntegration.java:331)
```

**Comment by sbrossie** [comment]
Fixed in https://github.com/killbill/killbill/pull/1526
