### ISSUE TITLE
Usage points when changing Plan on Create date may not be taken into account

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1511]
Kill Bill 's invoicing granularity is the day, and so we have made assumptions that  any `CHANGE` on an existing subscription that aligns perfectly with the `CREATE` event essentially replaces the original `CREATE` event.  See https://github.com/killbill/killbill/issues/733 and more specifically [this commit](https://github.com/killbill/killbill/commit/0752a2e7b03ff5ca365216b5b548a74261ab41ab).

Also, the [subscription#changePlan api](https://killbill.github.io/slate/#subscription-change-subscription-plan) takes a `LocalDate` as an argument, and so triggering a change of plan any time on the first day of the subscription would end up defaulting to the exact subscription#startdate.

This could prevent recoding usage point on the original Plan (first CREATE).

This is issue is a bit similar to https://github.com/killbill/killbill/issues/1438 (cancelation use case).

**Comment by sbrossie** [comment]
Also, worth noting the NPE that occurs when doing a `changePlan` on the first day for a subscription created with its own  BCD:

```
2021-10-05T15:15:52,176+0000 lvl='WARN', log='RuntimeExceptionMapper', th='qtp1648470764-62', xff='', rId='9805a1dd-42c0-4c81-88cf-e2770cac254f', tok='', aRId='2707', tRId='188', Unexpected NullPointerException
java.lang.NullPointerException: null
	at org.killbill.billing.subscription.api.user.DefaultSubscriptionBase.getSourceType(DefaultSubscriptionBase.java:196)
	at org.killbill.billing.entitlement.api.DefaultEntitlement.getSourceType(DefaultEntitlement.java:253)
	at org.killbill.billing.jaxrs.json.SubscriptionJson.<init>(SubscriptionJson.java:389)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.getSubscription(SubscriptionResource.java:173)
```
