### ISSUE TITLE
Trigger the generate invoice api cause a lock acquire fail

### ISSUE THREAD

**Issue by wishma2013** [killbill/killbill#1554]
The error log is like:
2021-12-22T10:18:46,867+0000 lvl='WARN', log='GlobalLockerBase', th='http-bio-8181-exec-2', xff='', rId='', tok='c3d1b766-be1a-42ca-882f-6903ea19954c', aRId='18294', tRId='1', Failed to acquire lock 0d158ca6-b6c1-4b4a-8af8-69ef35f231de for service ACCNT_INV_PAY after 50 retries

The stacktrace is like:
2021-12-22T10:41:36,695+0000 lvl='WARN', log='ProxyLeakTask', th='main housekeeper', xff='', rId='', tok='', aRId='', tRId='', Connection leak detection triggered for org.mariadb.jdbc.MariaDbConnection@58cf11f6 on thread http-bio-8181-exec-1, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at net.sf.log4jdbc.sql.jdbcapi.DataSourceSpy.getConnection(DataSourceSpy.java:147)
	at org.killbill.commons.locker.GlobalLockerBaseWithDao.doLock(GlobalLockerBaseWithDao.java:72)
	at org.killbill.commons.locker.GlobalLockerBase.lock(GlobalLockerBase.java:90)
	at org.killbill.commons.locker.GlobalLockerBase$1.execute(GlobalLockerBase.java:58)
	at org.killbill.commons.locker.GlobalLockerBase$1.execute(GlobalLockerBase.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.commons.locker.GlobalLockerBase.lockWithNumberOfTries(GlobalLockerBase.java:52)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:316)
	at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerInvoiceGeneration(DefaultInvoiceUserApi.java:284)

**Comment by wishma2013** [comment]
> The error log is like: 2021-12-22T10:18:46,867+0000 lvl='WARN', log='GlobalLockerBase', th='http-bio-8181-exec-2', xff='', rId='', tok='c3d1b766-be1a-42ca-882f-6903ea19954c', aRId='18294', tRId='1', Failed to acquire lock 0d158ca6-b6c1-4b4a-8af8-69ef35f231de for service ACCNT_INV_PAY after 50 retries
> 
> The stacktrace is like: 2021-12-22T10:41:36,695+0000 lvl='WARN', log='ProxyLeakTask', th='main housekeeper', xff='', rId='', tok='', aRId='', tRId='', Connection leak detection triggered for org.mariadb.jdbc.MariaDbConnection@58cf11f6 on thread http-bio-8181-exec-1, stack trace follows java.lang.Exception: Apparent connection leak detected at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) at net.sf.log4jdbc.sql.jdbcapi.DataSourceSpy.getConnection(DataSourceSpy.java:147) at org.killbill.commons.locker.GlobalLockerBaseWithDao.doLock(GlobalLockerBaseWithDao.java:72) at org.killbill.commons.locker.GlobalLockerBase.lock(GlobalLockerBase.java:90) at org.killbill.commons.locker.GlobalLockerBase$1.execute(GlobalLockerBase.java:58) at org.killbill.commons.locker.GlobalLockerBase$1.execute(GlobalLockerBase.java:52) at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35) at org.killbill.commons.locker.GlobalLockerBase.lockWithNumberOfTries(GlobalLockerBase.java:52) at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:316) at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerInvoiceGeneration(DefaultInvoiceUserApi.java:284)

How to add labels on this issue item?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
