### ISSUE TITLE
Trigger the generate invoice api cause a lock acquire fail

### ISSUE THREAD

**Issue by wishma2013** [killbill/killbill#1555]
**The error log is like:**
`2021-12-22T10:18:46,867+0000 lvl='WARN', log='GlobalLockerBase', th='http-bio-8181-exec-2', xff='', rId='', tok='c3d1b766-be1a-42ca-882f-6903ea19954c', aRId='18294', tRId='1', Failed to acquire lock 0d158ca6-b6c1-4b4a-8af8-69ef35f231de for service ACCNT_INV_PAY after 50 retries`

**The stack trace is like:**
`2021-12-22T10:41:36,695+0000 lvl='WARN', log='ProxyLeakTask', th='main housekeeper', xff='', rId='', tok='', aRId='', tRId='', Connection leak detection triggered for org.mariadb.jdbc.MariaDbConnection@58cf11f6 on thread http-bio-8181-exec-1, stack trace follows
java.lang.Exception: Apparent connection leak detected
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
at net.sf.log4jdbc.sql.jdbcapi.DataSourceSpy.getConnection(DataSourceSpy.java:147)
at org.killbill.commons.locker.GlobalLockerBaseWithDao.doLock(GlobalLockerBaseWithDao.java:72)
at org.killbill.commons.locker.GlobalLockerBase.lock(GlobalLockerBase.java:90)
at org.killbill.commons.locker.GlobalLockerBase$1.execute(GlobalLockerBase.java:58)
at org.killbill.commons.locker.GlobalLockerBase$1.execute(GlobalLockerBase.java:52)
at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
at org.killbill.commons.locker.GlobalLockerBase.lockWithNumberOfTries(GlobalLockerBase.java:52)
at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:316)
at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerInvoiceGeneration(DefaultInvoiceUserApi.java:284)
……`

**The database is mysql, and its data is like:**
_notifications table:_
![notification-data](https://user-images.githubusercontent.com/3312547/147166428-1e2c87a8-78f3-48f0-b06c-f40503fb924e.png)
_subscription_events table:_
![18294-bug-subscription_events](https://user-images.githubusercontent.com/3312547/147167150-fdcf2c9c-ad36-4490-9bc3-f32607774132.png)

The account of record id `18294` and `1474` are both our test account and have a lot of subscriptions with themselves.`18294` was new created recently.When I trigger the invoice generator api ,the error above was thrown.

**OS**：`CentOS 7`
**OS cpuinfo:**
`$ cat /proc/cpuinfo |grep "model name" && cat /proc/cpuinfo |grep "physical id"
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
model name	: AMD EPYC Processor
physical id	: 0
physical id	: 1
physical id	: 2
physical id	: 3
physical id	: 4
physical id	: 5
physical id	: 6
physical id	: 7`

**Comment by reshmabidikar** [comment]
Addressed in https://github.com/killbill/killbill/issues/1889. Closing this ticket.
