### ISSUE TITLE
Shiro login fails with UnknownSessionException: There is no session with id 

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1635]
It looks like in some situations, users report the shiro `login` process to fail with the following:

```
org.apache.shiro.session.UnknownSessionException: There is no session with id [REDACTED]
		at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:170)
		at org.apache.shiro.session.mgt.eis.CachingSessionDAO.readSession(CachingSessionDAO.java:261)
		at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)
		at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222)
		at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118)
		at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148)
		at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152)
		at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249)
		at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141)
		at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121)
		at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121)
		at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:469)
		at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:153)
		at org.apache.shiro.mgt.DefaultSecurityManager.logout(DefaultSecurityManager.java:547)
		at org.apache.shiro.subject.support.DelegatingSubject.logout(DelegatingSubject.java:363)
		at org.killbill.billing.util.security.api.DefaultSecurityApi.logout(DefaultSecurityApi.java:112)
		at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
		at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
		at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
		at org.killbill.billing.util.security.api.DefaultSecurityApi.login(DefaultSecurityApi.java:78)
		at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.exfecute(KillbillApiAopModule.java:76)
		at org.killbill.billing.util.entity.dao.DBRouterUntyped.withRODBIAllowed(DBRouterUntyped.java:57)
		at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$2.execute(KillbillApiAopModule.java:88)
		at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
		at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:83)
```

**Comment by sbrossie** [comment]
After looking into the issue, I suspect there may be concurrent operations and the [login](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/security/api/DefaultSecurityApi.java#L90) may fail because a concurrent logout just occurred, cleaning the session.

I think we should just catch the exception and continue the login path.
