### ISSUE TITLE
Issue is caching catalog with Redis cache

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1770]
When Redis cache is used, there is an issue in storing the catalog in the cache. The `StandaloneCatalogWithPriceOverride#priceOverride` field does not get stored in the cache. So, when the catalog is retrieved from the cache, this field is null and results in a `NullPointerException`.

Steps to reproduce:
1. Configure Redis cache
2. Ensure that a tenant exists with a catalog
3. Create a new account
4. Create a subscription to any plan in the catalog

This results in the following exception:

````
2022-08-31T19:58:31,738+0000 lvl='WARN', log='RuntimeExceptionMapper', th='catalina-exec-5', xff='', rId='', tok='5eccec61-0927-4fe9-966d-02b77dbffdb1', aRId='5', tRId='1', Unexpected NullPointerException
java.lang.NullPointerException: null
	at org.killbill.billing.catalog.StandaloneCatalogWithPriceOverride.findPlan(StandaloneCatalogWithPriceOverride.java:98)
	at org.killbill.billing.catalog.StandaloneCatalog.createOrFindPlan(StandaloneCatalog.java:209)
	at org.killbill.billing.catalog.StandaloneCatalogWithPriceOverride.createOrFindPlan(StandaloneCatalogWithPriceOverride.java:84)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionBaseCreateApi.createPlansIfNeededAndReorderBPOrStandaloneSpecFirstWithSanity(DefaultSubscriptionBaseCreateApi.java:295)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionBaseCreateApi.prepareSubscriptionAndAddOnsSpecifier(DefaultSubscriptionBaseCreateApi.java:131)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionBaseCreateApi.createBaseSubscriptionsWithAddOns(DefaultSubscriptionBaseCreateApi.java:80)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.createBaseSubscriptionsWithAddOns(DefaultSubscriptionInternalApi.java:150)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi$5.doCall(DefaultEntitlementApi.java:459)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi$5.doCall(DefaultEntitlementApi.java:407)
	at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:97)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi.createBaseEntitlementsWithAddOns(DefaultEntitlementApi.java:477)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi.createBaseEntitlementsWithAddOns(DefaultEntitlementApi.java:158)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:89)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:105)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doOperation(SubscriptionResource.java:386)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doOperation(SubscriptionResource.java:365)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$EntitlementCallCompletion.withSynchronization(SubscriptionResource.java:836)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.createSubscriptionsWithAddOnsInternal(SubscriptionResource.java:426)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource_$$_jvst43_5._d27createSubscriptionsWithAddOnsInternal(SubscriptionResource_$$_jvst43_5.java)
````

**Comment by reshmabidikar** [comment]
The proposed fix to this issue would be to invoke `initializeCatalog` after the catalog is retrieved from the cache [here](https://github.com/killbill/killbill/blob/ff81c701e236310561e31624df18bab5788b0339/catalog/src/main/java/org/killbill/billing/catalog/caching/DefaultCatalogCache.java#L133). However, this fix needs to be implemented carefully as this had some performance issues due to which it was removed as part of [this commit](https://github.com/killbill/killbill/commit/47a39117124f6f69921a817d2c19a8fcd16842f8).

**Comment by nick-at-finix** [comment]
Hi team, is there any workarounds for this issue? We just set up Redis so that we can have a shared cache for our kubernetes deployment of Killbill (to avoid issues with catalog caching being inconsistent between nodes), and this issue is blocking us from using redis.
