### ISSUE TITLE
ClassNotFoundException when running load-tool

### ISSUE THREAD

**Issue by arturhefczyc** [killbill/killbill#1790]
I am going through documentation and trying examples. However, I encountered problem right in the beginning trying the load-tool:
```
~/projects/killbill$ java -jar killbill-catalog-0.22.9-load-tool.jar SpyCarBasic.xml 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at org.killbill.xmlloader.XMLLoader.unmarshaller(XMLLoader.java:109)
	at org.killbill.xmlloader.XMLLoader.getObjectFromStream(XMLLoader.java:69)
	at org.killbill.xmlloader.XMLLoader.getObjectFromUri(XMLLoader.java:61)
	at org.killbill.billing.catalog.LoadCatalog.main(LoadCatalog.java:33)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more
~/projects/killbill$ java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.1 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode)
```
Do you have any suggestion?

**Comment by arturhefczyc** [comment]
Ok, found a workaround which is working and acceptable to me.
1. Download JAXB from github: https://javaee.github.io/jaxb-v2/
2. Unzip the file
3. Run the killbill-catalog-load-tool in the following way:
```
java -cp "killbill-catalog-0.22.9-load-tool.jar:jaxb-ri/mod/*" org.killbill.billing.catalog.LoadCatalog SpyCarBasic.xml
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Success: Catalog loads!
```

However, if you have a "proper" solution, please let me know.

**Comment by KBbitsP** [comment]
Hi @arturhefczyc 

Please use the latest version here https://repo1.maven.org/maven2/org/kill-bill/billing/killbill-catalog/0.24.0. 

![image](https://user-images.githubusercontent.com/75751774/208293772-11761e21-5329-44a2-ab1d-0a6e2e2d8cc7.png)

Regards
Karan

**Comment by arturhefczyc** [comment]
Thank you.
