### ISSUE TITLE
Installation error on Debian

### ISSUE THREAD

**Issue by barf** [killbill/killbill#1897]
Hello I'm trying to install 0.24.4 on Debian and PostgreSQL following the Getting Started guide docs here: https://docs.killbill.io/latest/PostgreSQL.html#_postgresql_configuration

But I can get no further than this `NoSuchObjectException: no such object in table` error, are some ddls missing from the documentation maybe?

To reproduce this I simply follow the installation guide, after installing ROOT.war into Tomcat and bringing in the SQL schemas in the guide Tomcat fails to start:
```
2023-08-01T02:23:11,345+0000 lvl='WARN', log='JNDIManager', th='localhost-startStop-1', xff='', rId='', tok='', aRId='', tRId='', Error exporting killbill/osgi/jdbc
javax.naming.CommunicationException: null
	at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.rebind(RegistryContext.java:178)
	at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.rebind(RegistryContext.java:183)
	at java.naming/javax.naming.InitialContext.rebind(InitialContext.java:425)
	at org.killbill.billing.platform.jndi.JNDIManager.doExport(JNDIManager.java:116)
	at org.killbill.billing.platform.jndi.JNDIManager.export(JNDIManager.java:68)
	at org.killbill.billing.osgi.KillbillActivator.start(KillbillActivator.java:209)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix$SystemBundleActivator.start(Felix.java:5126)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.init(Felix.java:899)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at org.killbill.billing.osgi.DefaultOSGIService.createAndInitFelixFrameworkWithSystemBundle(DefaultOSGIService.java:168)
	at org.killbill.billing.osgi.DefaultOSGIService.createAndInitFramework(DefaultOSGIService.java:153)
	at org.killbill.billing.osgi.DefaultOSGIService.initialize(DefaultOSGIService.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.killbill.billing.lifecycle.DefaultLifecycle.doFireStage(DefaultLifecycle.java:155)
	at org.killbill.billing.lifecycle.DefaultLifecycle.fireSequence(DefaultLifecycle.java:142)
	at org.killbill.billing.lifecycle.DefaultLifecycle.fireStartupSequencePriorEventRegistration(DefaultLifecycle.java:76)
	at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.startLifecycle(KillbillPlatformGuiceListener.java:210)
	at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.contextInitialized(KillbillPlatformGuiceListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4477)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4935)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:710)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:687)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.rmi.NoSuchObjectException: no such object in table
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:380)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.rebind(RegistryImpl_Stub.java:158)
	at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.rebind(RegistryContext.java:176)
	... 35 common frames omitted
```

**Comment by barf** [comment]
ignore this it's working! added ?currentSchema=killbillschema to the jdbc string for good measure and this error is apparently benign

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) in the future. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
