### ISSUE TITLE
Issue with default value of updated_date column in the invoice_tracking_ids table

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1900]
Our [DDL](https://github.com/killbill/killbill/blob/master/invoice/src/main/resources/org/killbill/billing/invoice/ddl.sql#L16) specifies a non-null value for the `updated_date` column in the `invoice_tracking_ids` table. So, the [schema migration](https://github.com/killbill/killbill/blob/master/invoice/src/main/resources/org/killbill/billing/invoice/migration/V20190121141325__tracking_ids_is_active.sql#L3) specifies a default value of `1970-01-01 00:00:00` for this column.  However, some customers have reported that this results in the following `ParserException` when the analytics plugin starts:

````
2023-07-17T19:39:52,634+0000 lvl='INFO', log='Metadata', th='Thread-8', xff='', rId='', tok='', aRId='', tRId='', Started priming caches...
2023-07-17T19:39:53,550+0000 lvl='INFO', log='MetaImpl', th='Thread-8', xff='', rId='', tok='', aRId='', tRId='', Cannot parse default expression: 1970-01-01 00:00:00
2023-07-17T19:39:53.551213716Z org.jooq.impl.ParserException: Unexpected content after end of field input: [1:12] 1970-01-01 [*]00:00:00
2023-07-17T19:39:53.551217132Z  at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:13544)
2023-07-17T19:39:53.551219216Z  at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:13704)
2023-07-17T19:39:53.551220924Z  at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:563)
2023-07-17T19:39:53.551222632Z  at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:428)
2023-07-17T19:39:53.551224174Z  at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:423)
2023-07-17T19:39:53.551225882Z  at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1084)
2023-07-17T19:39:53.551227591Z  at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:679)
2023-07-17T19:39:53.551229382Z  at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:425)
2023-07-17T19:39:53.551231674Z  at org.jooq.impl.Tools.map(Tools.java:2020)
2023-07-17T19:39:53.551233341Z  at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:397)
2023-07-17T19:39:53.551235049Z  at org.killbill.billing.plugin.analytics.reports.sql.Metadata.getTable(Metadata.java:140)
2023-07-17T19:39:53.551236674Z  at org.killbill.billing.plugin.analytics.reports.sql.Metadata.getTable(Metadata.java:87)
2023-07-17T19:39:53.551238299Z  at org.killbill.billing.plugin.analytics.reports.sql.Metadata$3.run(Metadata.java:234)
2023-07-17T19:39:53.560701049Z 2023-07-17T19:39:53,560+0000 lvl='INFO', log='Metadata', th='Thread-8', xff='', rId='', tok='', aRId='', tRId='', Primed caches in 0:00
````

**Comment by sbrossie** [comment]
I was able to reproduce the issue by first dropping the column `updated_date` and then adding it again using the migration command: `alter table invoice_tracking_ids add column updated_date datetime NOT NULL DEFAULT '1970-01-01 00:00:00' after updated_by;`

It really looks like a jooq issue not being able to parse the schema:

```
Create Table: CREATE TABLE `invoice_tracking_ids` (
  `record_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id` varchar(36) COLLATE utf8mb3_bin NOT NULL,
  `tracking_id` varchar(128) COLLATE utf8mb3_bin NOT NULL,
  `invoice_id` varchar(36) COLLATE utf8mb3_bin NOT NULL,
  `subscription_id` varchar(36) COLLATE utf8mb3_bin DEFAULT NULL,
  `unit_type` varchar(255) COLLATE utf8mb3_bin NOT NULL,
  `record_date` date NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` varchar(50) COLLATE utf8mb3_bin NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` varchar(50) COLLATE utf8mb3_bin NOT NULL,
  `updated_date` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `account_record_id` bigint unsigned NOT NULL,
  `tenant_record_id` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`record_id`),
  UNIQUE KEY `record_id` (`record_id`),
  KEY `invoice_tracking_tenant_account_date_idx` (`tenant_record_id`,`account_record_id`,`record_date`),
  KEY `invoice_tracking_invoice_id_idx` (`invoice_id`),
  KEY `invoice_tracking_id_idx` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin

```

**Comment by sbrossie** [comment]
The workaround is to remove the default value (after ensuring that each row has a default value).

**Comment by sbrossie** [comment]
See bug filed on jOOQ side: https://github.com/jOOQ/jOOQ/issues/15486
