### ISSUE TITLE
"Unable to retrieve Kill Bill version" when upgrading from 0.22.31 to 0.24.4 (in docker)

### ISSUE THREAD

**Issue by woj-tek** [killbill/killbill#1903]
tl,dr;

There seems to be a couple of bugs in upgrade process:
1) migrations reference missing `/var/lib/tomcat/webapps/ROOT.war` (there is unpacked directory)
2) `https://github.com/killbill/killbill-cloud/blob/master/kpm/lib/kpm/migrations.rb` seems to have a bug - missing imports (`require 'net/http'` and `require 'net/https'`)

There is still issue with 401 error from ruby...

---

Following guide: https://docs.killbill.io/latest/database_migrations.html#_migrations_with_docker_images

```
TASK [migrations : fetch all migrations] *****************************************************************************************************************************************************************************
task path: /var/lib/tomcat/.ansible/roles/killbill-cloud/ansible/roles/migrations/tasks/main.yml:2
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to retrieve Kill Bill version"}
```

Debug log:
```
2023-08-11 12:13:55,242 p=1140 u=tomcat n=ansible |   1140 1691756035.24256: done with local.exec_command()
2023-08-11 12:13:55,242 p=1140 u=tomcat n=ansible |   1140 1691756035.24279: _low_level_execute_command() done: rc=1, stdout={"failed":true,"msg":"Unable to retrieve Kill Bill version"}, stderr=
2023-08-11 12:13:55,243 p=1140 u=tomcat n=ansible |   1140 1691756035.24315: done with _execute_module (killbill_migrations, {'kpm_path': '/opt/kpm-latest', 'bundles_dir': '/var/lib/killbill/bundles', 'kaui_web_path': '/var/lib/tomcat/webapps/ROOT.war', 'killbill_web_path': '/var/lib/tomcat/webapps/ROOT.war', 'kpm_yml': '/var/lib/killbill/kpm.yml', 'gh_token': '', '_ansible_check_mode': False, '_ansible_no_log': False, '_ansible_debug': True, '_ansible_diff': False, '_ansible_verbosity': 2, '_ansible_version': '2.9.6', '_ansible_module_name': 'killbill_migrations', '_ansible_syslog_facility': 'LOG_USER', '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p', 'vfat'], '_ansible_string_conversion_action': 'warn', '_ansible_socket': None, '_ansible_shell_executable': '/bin/sh', '_ansible_keep_remote_files': False, '_ansible_tmpdir': '/var/lib/tomcat/.ansible/tmp/ansible-tmp-1691756034.724211-129720927686073/', '_ansible_remote_tmp': '~/.ansible/tmp'})
2023-08-11 12:13:55,243 p=1140 u=tomcat n=ansible |   1140 1691756035.24339: _low_level_execute_command(): starting
2023-08-11 12:13:55,243 p=1140 u=tomcat n=ansible |   1140 1691756035.24383: _low_level_execute_command(): executing: /bin/sh -c 'rm -f -r /var/lib/tomcat/.ansible/tmp/ansible-tmp-1691756034.724211-129720927686073/ > /dev/null 2>&1 && sleep 0'
2023-08-11 12:13:55,244 p=1140 u=tomcat n=ansible |   1140 1691756035.24396: in local.exec_command()
2023-08-11 12:13:55,244 p=1140 u=tomcat n=ansible |   1140 1691756035.24412: opening command with Popen()
2023-08-11 12:13:55,247 p=1140 u=tomcat n=ansible |   1140 1691756035.24725: done running command with Popen()
2023-08-11 12:13:55,247 p=1140 u=tomcat n=ansible |   1140 1691756035.24751: getting output with communicate()
2023-08-11 12:13:55,250 p=1140 u=tomcat n=ansible |   1140 1691756035.25005: done communicating
2023-08-11 12:13:55,250 p=1140 u=tomcat n=ansible |   1140 1691756035.25019: done with local.exec_command()
2023-08-11 12:13:55,250 p=1140 u=tomcat n=ansible |   1140 1691756035.25036: _low_level_execute_command() done: rc=0, stdout=, stderr=
2023-08-11 12:13:55,250 p=1140 u=tomcat n=ansible |   1140 1691756035.25055: handler run complete
2023-08-11 12:13:55,250 p=1140 u=tomcat n=ansible |   1140 1691756035.25094: attempt loop complete, returning result
2023-08-11 12:13:55,251 p=1140 u=tomcat n=ansible |   1140 1691756035.25112: _execute() done
2023-08-11 12:13:55,251 p=1140 u=tomcat n=ansible |   1140 1691756035.25125: dumping result to json
2023-08-11 12:13:55,251 p=1140 u=tomcat n=ansible |   1140 1691756035.25138: done dumping result, returning
2023-08-11 12:13:55,251 p=1140 u=tomcat n=ansible |   1140 1691756035.25161: done running TaskExecutor() for localhost/TASK: migrations : fetch all migrations [ea7b3e9b-a943-7297-deec-000000000021]
2023-08-11 12:13:55,251 p=1140 u=tomcat n=ansible |   1140 1691756035.25192: sending task result for task ea7b3e9b-a943-7297-deec-000000000021
2023-08-11 12:13:55,252 p=1140 u=tomcat n=ansible |   1140 1691756035.25242: done sending task result for task ea7b3e9b-a943-7297-deec-000000000021
2023-08-11 12:13:55,252 p=1140 u=tomcat n=ansible |   1140 1691756035.25288: WORKER PROCESS EXITING
2023-08-11 12:13:55,254 p=952 u=tomcat n=ansible |    952 1691756035.25404: marking localhost as failed
2023-08-11 12:13:55,254 p=952 u=tomcat n=ansible |    952 1691756035.25436: marking host localhost failed, current state: HOST STATE: block=4, task=1, rescue=0, always=0, run_state=ITERATING_TASKS, fail_state=FAILED_NONE, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
2023-08-11 12:13:55,254 p=952 u=tomcat n=ansible |    952 1691756035.25455: ^ failed state is now: HOST STATE: block=4, task=1, rescue=0, always=0, run_state=ITERATING_COMPLETE, fail_state=FAILED_TASKS, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
2023-08-11 12:13:55,255 p=952 u=tomcat n=ansible |    952 1691756035.25473: getting the next task for host localhost
2023-08-11 12:13:55,255 p=952 u=tomcat n=ansible |    952 1691756035.25511: host localhost is done iterating, returning
2023-08-11 12:13:55,255 p=952 u=tomcat n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to retrieve Kill Bill version"}
```

I checked the paths and there seems to be an error - there isn't any `ROOT.war` but only `ROOT` directory (which seems to be extracted `ROOT.war`)

```
tomcat@killbill-84955cd88b-skgfv:~$ file /var/lib/tomcat/webapps/ROOT.war
bash: file: command not found

tomcat@killbill-84955cd88b-skgfv:~$ ls -lah /var/lib/tomcat/webapps/ROOT
total 16K
drwxr-xr-x. 7 tomcat tomcat  135 Oct  2  2022 .
drwxr-xr-x. 1 tomcat tomcat   18 Oct  2  2022 ..
drwxr-xr-x. 3 tomcat tomcat   38 Oct  2  2022 META-INF
drwxr-xr-x. 4 tomcat tomcat   47 Oct  2  2022 WEB-INF
-rw-r--r--. 1 tomcat tomcat 2.4K Oct  2  2022 api.html
drwxr-xr-x. 2 tomcat tomcat  137 Oct  2  2022 css
drwxr-xr-x. 2 tomcat tomcat  151 Oct  2  2022 images
-rw-r--r--. 1 tomcat tomcat 2.5K Oct  2  2022 index.html
drwxr-xr-x. 2 tomcat tomcat 4.0K Oct  2  2022 lib
-rw-r--r--. 1 tomcat tomcat 2.4K Oct  2  2022 oauth2-redirect.html
```

I zipped the contents into `ROOT.war` and it still resulted in failure:
```
TASK [migrations : fetch all migrations] *****************************************************************************************************************************************************************************
task path: /var/lib/tomcat/.ansible/roles/killbill-cloud/ansible/roles/migrations/tasks/main.yml:2
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:85:in `get_as_json': uninitialized constant KPM::Migrations::Net (NameError)\nDid you mean?  Set\n\tfrom /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:57:in `for_version'\n\tfrom /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:30:in `migrations'\n\tfrom /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:38:in `save'\n\tfrom /var/lib/tomcat/.ansible/tmp/ansible-tmp-1691772777.884947-18220907991139/AnsiballZ_killbill_migrations:70:in `<main>'\n", "module_stdout": "I, [2023-08-11T16:52:58.399128 #3244]  INFO -- : Looking for migrations repository=killbill/killbill, version=killbill-0.22.31\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Looking at the stacktrace:
```
  3490 1691772839.65074: _low_level_execute_command() done: rc=1, stdout=I, [2023-08-11T16:53:59.647180 #3507]  INFO -- : Looking for migrations repository=killbill/killbill, version=killbill-0.22.31
, stderr=/opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:85:in `get_as_json': uninitialized constant KPM::Migrations::Net (NameError)
Did you mean?  Set
	from /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:57:in `for_version'
	from /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:30:in `migrations'
	from /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:38:in `save'
```

It seems that https://github.com/killbill/killbill-cloud/blob/master/kpm/lib/kpm/migrations.rb lacks:
```rb
require 'net/http'
require 'net/https'
```

It fixes the ruby issue but then there is another error:
```
  4036 1691773320.12681: _low_level_execute_command() done: rc=1, stdout=I, [2023-08-11T17:01:59.888818 #4053]  INFO -- : Looking for migrations repository=killbill/killbill, version=killbill-0.22.31
, stderr=/opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:101:in `get_as_json': Unable to download https://api.github.com/repos/killbill/killbill/git/trees/killbill-0.22.31?recursive=1: 401 (RuntimeError)
	from /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:60:in `for_version'
	from /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:33:in `migrations'
	from /opt/kpm-0.10.5-linux-x86_64/lib/vendor/ruby/2.6.0/gems/kpm-0.10.5/lib/kpm/migrations.rb:41:in `save'
	from /var/lib/tomcat/.ansible/tmp/ansible-tmp-1691773319.2483099-94184517231977/AnsiballZ_killbill_migrations:70:in `<main>'
```

This is quite odd as I can access this URL both from my local machine as well as via `curl` from within docker container, where the error happens:

```
tomcat@killbill-84955cd88b-skgfv:~$ curl  https://api.github.com/repos/killbill/killbill/git/trees/killbill-0.22.31?recursive=1
{
  "sha": "5c63f41b26de4f145d15ba0f3fa2fc3c1b8866e9",
  "url": "https://api.github.com/repos/killbill/killbill/git/trees/5c63f41b26de4f145d15ba0f3fa2fc3c1b8866e9",
  "tree": [
    {
      "path": ".circleci",
      "mode": "040000",
      "type": "tree",
      "sha": "49c818303068430eeb20c6ba79532e606b465a6c",
      "url": "https://api.github.com/repos/killbill/killbill/git/trees/49c818303068430eeb20c6ba79532e606b465a6c"
    },
    {
…
```

(I created message in the group, but this seems like a bug hence reporting it here as well)

**Comment by woj-tek** [comment]
Removing setting of Auth header (basically [`request['Authorization'] = "token #{@oauth_token}" unless @oauth_token.nil?`](https://github.com/killbill/killbill-cloud/blob/master/kpm/lib/kpm/migrations.rb#L91) line) "fixed" the problem with 404 error, but then new one appeared... and I'm a bit at loss as the stacktrace doesn't point to existing file - I assume it's somehow generated during the whole process...:

```
I, [2023-08-11T17:33:44.119778 #5155]  INFO -- : Migration to run: V2022070713524522__record_date_time.sql
, stderr=/var/lib/tomcat/.ansible/tmp/ansible-tmp-1691775221.3132408-268460853268668/AnsiballZ_killbill_migrations:93:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/tomcat/.ansible/tmp/ansible-tmp-1691775221.3132408-268460853268668/AnsiballZ_killbill_migrations:81:in `each'
	from /var/lib/tomcat/.ansible/tmp/ansible-tmp-1691775221.3132408-268460853268668/AnsiballZ_killbill_migrations:81:in `<main>'
  5138 1691775224.12619: done with _execute_module (killbill_migrations, {'kpm_path': '/opt/kpm-latest', 'bundles_dir': '/var/lib/killbill/bundles', 'kaui_web_path': '/var/lib/tomcat/webapps/ROOT.war', 'killbill_web_path': '/var/lib/tomcat/webapps/ROOT.war', 'kpm_yml': '/var/lib/killbill/kpm.yml', 'gh_token': '', '_ansible_check_mode': False, '_ansible_no_log': False, '_ansible_debug': True, '_ansible_diff': False, '_ansible_verbosity': 2, '_ansible_version': '2.9.6', '_ansible_module_name': 'killbill_migrations', '_ansible_syslog_facility': 'LOG_USER', '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p', 'vfat'], '_ansible_string_conversion_action': 'warn', '_ansible_socket': None, '_ansible_shell_executable': '/bin/sh', '_ansible_keep_remote_files': False, '_ansible_tmpdir': '/var/lib/tomcat/.ansible/tmp/ansible-tmp-1691775
```

**Comment by reshmabidikar** [comment]
Thanks for the report. I've filed https://github.com/killbill/killbill-cloud/issues/273 to track this issue. I'm closing this ticket.
