### ISSUE TITLE
NodesInfo corrupted on misconfigured k8s environments

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#2061]
Scenario: Kill Bill deployed with default configuration in a k8s environment, with a single pod. `helm upgrade` is used to roll Kill Bill with the following strategy:

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
```

The update takes place with zero downtime, i.e., the new pods are scheduled on nodes with available resources, and k8s waits for those new pods to start before removing the old Pods.

This should be well supported with Kill Bill except that the default configuration shouldn't be used in a k8s environment: `CreatorName` will likely default to `localhost` (https://github.com/killbill/killbill-commons/blob/5bb6eb34b6e686bf30e215ab2eb6a0d68124d307/queue/src/main/java/org/killbill/CreatorName.java#L44), so all running pods during the deployment rollout will use the same name.

The new pod will start and create the entry (`Created nodeInfo for localhost` -- this actually upserts it, since the entry is already there). The old pod is then shut down (`Deleting nodeInfo for localhost` -- and the table is now empty).

If you are seeing these errors in your logs and run in a k8s environment, you are likely hitting this bug:

```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at org.killbill.billing.util.nodes.DefaultKillbillNodesApi.getCurrentNodeInfo(DefaultKillbillNodesApi.java:80)
```

```
DBBackedQueue-notifications reapEntries: stuck queue entries [NotificationEventModelDao{recordId=1759, className='**************************************************************', eventJson='{"attemptId":"8d53dced-0976-4947-ad91-73116338b025","paymentControlPluginNames":["__INVOICE_PAYMENT_CONTROL_PLUGIN__"]}', userToken=null, createdDate=2024-07-14T22:01:30.000Z, creatingOwner='localhost', processingOwner='localhost', processingAvailableDate=2024-07-22T22:06:29.000Z, errorCount=0, processingState=IN_PROCESSING, searchKey1=2, searchKey2=7, futureUserToken=16c2e677-bde0-4c51-b5d3-b891e3201365, effectiveDate=2024-07-22T22:01:29.000Z, queueName='*********************'}]
```

In a k8s environment, `KILLBILL_QUEUE_CREATOR_NAME` should always be set to something unique to the pod. But we should strengthen the code by default:

* We will introduce `org.killbill.queue.creator.autoGeneratedName`. If `true` and if `org.killbill.queue.creator.name` isn't set, we'll generate a UUID instead of using the local address
* We'll update our Docker images to set it to true by default, such that in all cloud-native environments (k8s, ecs, etc.) using our Docker images, the name is autogenerated by default

**Comment by nick-at-finix** [comment]
We have worked around this issue with the following environment variable:
```
          env:
            - name: KILLBILL_QUEUE_CREATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
```

```
➜  ~ curl -s -u $USER_PWD https://mycompany.com/1.0/kb/nodesInfo | jq '.[]| .nodeName'

"killbill-b5c9fb65c-kqk6h"
```
