### ISSUE TITLE
The last packet successfully received from the server was x milliseconds ago

### ISSUE THREAD

**Issue by cholcombe973** [killbill/killbill#220]
I'm running killbill inside a docker container and I'm seeing a ton of these errors:  

The last packet successfully received from the server was 57,055 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago. [statement:"getReadyEntries", located:"    select
                 record_id
                  ,       class_name
                  , event_json
                  , user_token
                  , created_date
                  , creating_owner
                  , processing_owner
                  , processing_available_date
                  , processing_state
                  , error_count
                  , search_key1
                  , search_key2

    from bus_ext_events
    where
          processing_state != 'PROCESSED'
          and processing_state != 'REMOVED'
          and (processing_owner IS NULL OR processing_available_date <= :now)
    order by
          record_id asc
    limit :max
    ;", rewritten:"    select
                 record_id
                  ,       class_name
                  , event_json
                  , user_token
                  , created_date
                  , creating_owner
                  , processing_owner
                  , processing_available_date
                  , processing_state
                  , error_count
                  , search_key1
                  , search_key2

    from bus_ext_events
    where
          processing_state != 'PROCESSED'
          and processing_state != 'REMOVED'
          and (processing_owner IS NULL OR processing_available_date <= ?)
    order by
          record_id asc
    limit ?
    ;", arguments:{ positional:{}, named:{max:5,now:Mon Aug 04 19:33:37 EDT 2014}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1334) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.Query.fold(Query.java:170) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.Query.list(Query.java:83) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:223) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:47) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:44) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:171) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:89) ~[jdbi-2.53.jar:2.53]
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$51c0c76c.getReadyEntries(<generated>) ~[jdbi-2.53.jar:2.53]
	at org.killbill.queue.DBBackedQueue.fetchReadyEntries(DBBackedQueue.java:477) ~[killbill-queue-0.2.15.jar:na]
	at org.killbill.queue.DBBackedQueue.getReadyEntries(DBBackedQueue.java:236) ~[killbill-queue-0.2.15.jar:na]
	at org.killbill.bus.DefaultPersistentBus.doProcessEvents(DefaultPersistentBus.java:93) ~[killbill-queue-0.2.15.jar:na]
	at org.killbill.queue.DefaultQueueLifecycle$1.run(DefaultQueueLifecycle.java:107) ~[killbill-queue-0.2.15.jar:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_25]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_25]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

It looks like packets are making it out but not back in.  If i use the mysql client inside the docker container I can select/insert just fine.  I'm not quite sure what is going on here.

**Comment by pierre** [comment]
Closing for lack of activity.

Docker is now officially supported, see https://killbill.io/blog/having-fun-with-docker-stripe-kill-bill/.
