### ISSUE TITLE
Payment state machine on plugin timeout

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#229]
Upon API calls, the payment system delegates the plugin task to a dispatcher thread; when this one times out, the main api thread continues in the state machine and gets routed based on the state machine state description.

Currently, the code return an OperationResult.EXCEPTION, which gets interpredted by the xml description as a ERRORED case:
* First issue is that most state machine define both an ERRORED and a FAILED state, but from what i am seeing there is no difference between the two; do we really need both then?
* Second issue is that in the case of a timeout we want the plugin thread to successfully move the state to SUCCESS when the plugin call completed successfully. There are 2 ways we could do that:
1. The plugin thread could link back into the state machine and define a LeavingStateCallback that correctly make the transition.
2. We could rely on the Janitor to have a task which checks the entries for which we had a timeout, and make the transition happen by asking the plugin whether the call completed successfully or not.
If looks like whether we chose 1/ or 2/ we may want to introduce a new state.

**Comment by pierre** [comment]
Just to confirm, here is what a timeout looks like today (we return 500):

```
2015-06-26 06:05:54,229 [Thread-20] INFO  o.k.b.k.0.4.0.SNAPSHOT - [cybersource-plugin] [ActiveMerchant::Billing::CyberSourceGateway] --> 200 OK (1572 3.6780s)
2015-06-26 06:05:54,229 [Thread-20] INFO  o.k.b.k.0.4.0.SNAPSHOT - [cybersource-plugin] [ActiveMerchant::Billing::CyberSourceGateway] connection_attempt=1 connection_request_time=3.6780s connection_msg="success"
2015-06-26 06:05:54,230 [Thread-20] INFO  o.k.b.k.0.4.0.SNAPSHOT - [cybersource-plugin] [ActiveMerchant::Billing::CyberSourceGateway] connection_request_total_time=3.6780s
2015-06-26 06:05:54,281 [qtp2061652146-31] ERROR o.k.b.p.c.sm.OperationCallbackBase - Plugin call TIMEOUT for account 1435323945-137499
2015-06-26 06:05:54,293 [qtp2061652146-31] WARN  o.k.b.j.mappers.ExceptionMapperBase - Internal error
org.killbill.billing.payment.api.PaymentApiException: Internal payment error : org.killbill.automaton.OperationException: java.util.concurrent.TimeoutException
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.runStateMachineOperation(PaymentAutomatonRunner.java:230)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.run(PaymentAutomatonRunner.java:195)
	at org.killbill.billing.payment.core.PaymentProcessor.performOperation(PaymentProcessor.java:326)
	at org.killbill.billing.payment.core.PaymentProcessor.createPurchase(PaymentProcessor.java:125)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createPurchase(DefaultPaymentApi.java:159)
```

payments state:

```
              record_id: 362245
                     id: 5170d510-48db-4859-8298-6604acc6bdb3
             account_id: bc90bf7b-3e56-4edc-820c-7ba5a349b41c
      payment_method_id: 4bb186dc-b633-47db-91d6-57edd80f4bec
           external_key: 1435323949
             state_name: PURCHASE_ERRORED
last_success_state_name: NULL
             created_by: test_broken_connection
           created_date: 2013-08-01 06:00:03
             updated_by: test_broken_connection
           updated_date: 2013-08-01 06:00:03
      account_record_id: 360993
       tenant_record_id: 1718
```

payment_transactions state:

```
               record_id: 362576
                      id: 157de226-6bfa-4f7b-86f4-89274f3a0e67
              attempt_id: NULL
transaction_external_key: 1435323949
        transaction_type: PURCHASE
          effective_date: 2013-08-01 06:00:03
      transaction_status: UNKNOWN
                  amount: 10.000000000
                currency: USD
        processed_amount: 10.000000000
      processed_currency: USD
              payment_id: 5170d510-48db-4859-8298-6604acc6bdb3
      gateway_error_code: NULL
       gateway_error_msg: NULL
              created_by: test_broken_connection
            created_date: 2013-08-01 06:00:03
              updated_by: test_broken_connection
            updated_date: 2013-08-01 06:00:03
       account_record_id: 360993
        tenant_record_id: 1718
```

The state in the plugin is all good though.

By issuing a GET request (`/1.0/kb/payments/5170d510-48db-4859-8298-6604acc6bdb3?withPluginInfo=true`), the state is fixed via https://github.com/killbill/killbill/issues/341:

```
o.k.b.p.c.janitor.CompletionTaskBase - Janitor IncompletePaymentTransactionTask repairing payment 5170d510-48db-4859-8298-6604acc6bdb3, transaction 157de226-6bfa-4f7b-86f4-89274f3a0e67, transitioning transactionStatus from UNKNOWN -> SUCCESS
```
