### ISSUE TITLE
Should account take the lock on update?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#282]
`AccountInternalApi` exposes an `updateAccount` method used by `DefaultInternalBillingApi` to update the BCD. This is done using the lock. However, the `DefaultAccountUserApi#updateAccount` APIs don't take it, which could make the BCD calculation wrong (see https://github.com/killbill/killbill/blob/master/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultInternalBillingApi.java#L181).

**Comment by pierre** [comment]
Related to this, the following stacktrace can happen under high concurrency:

```
org.killbill.billing.account.api.AccountApiException: Account update failed.
	at org.killbill.billing.account.api.svcs.DefaultAccountInternalApi.updateBCD(DefaultAccountInternalApi.java:95)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.addBillingEventsForSubscription(DefaultInternalBillingApi.java:216)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.addBillingEventsForBundles(DefaultInternalBillingApi.java:170)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.getBillingEventsForAccountAndUpdateAccountBCD(DefaultInternalBillingApi.java:111)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionStartRequestedDate(InvoiceDispatcher.java:197)
	at org.killbill.billing.invoice.InvoiceListener$5.run(InvoiceListener.java:164)
```

* Node 1: create subscription API call -> `DefaultRequestedSubscriptionEvent(CREATE)` event -> Invoice run (T2) -> BCD update (failure)
* Node 2: cancel subscription API call -> `DefaultRequestedSubscriptionEvent(CANCEL)` event -> Invoice run (T1) -> BCD update (success)

In this case, node 1 is late and T2 > T1, leading to the update error.

Note that today, this exception is swallowed: https://github.com/killbill/killbill/blob/1a32d05ea0405fe9221b5a58490da57532e52f58/invoice/src/main/java/org/killbill/billing/invoice/InvoiceDispatcher.java#L213 which could lead to a missing invoice generation.
