### ISSUE TITLE
Missing INSERT audit logs

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#287]
During a migration, I've seen the Analytics plugin warn a few times `Unable to find payment creation audit log for id XXXX` (affects `payment`, `subscription event`, `invoice` and `invoice item` objects).

The rows seem to be there and a subsequent refresh doesn't trigger a warning. Could it be a caching problem?

**Comment by pierre** [comment]
cc/ @kevinpostlewaite: have you seen this lately?

**Comment by kevinpostlewaite** [comment]
I don't remember ever seeing this. Would this have gone to killbill.out? I was looking at Splunk for killbill.out earlier this week and saw no instances of that message across all server instances in last 30 days.

**Comment by pierre** [comment]
It would have indeed gone into `killbill.out`. I'll keep the bug open for now, we can close it in the future if we cannot reproduce it.

**Comment by pierre** [comment]
Verified the `WARN` is still happening - however the data is present in the database.

**Comment by pierre** [comment]
Still present on 0.17.6.

**Comment by pierre** [comment]
Could be related: https://github.com/killbill/killbill/issues/711.

**Comment by pierre** [comment]
Unfortunately, this is still happening with 0.18.4.

**Comment by pierre** [comment]
Couldn't reproduce on 0.21.3.

**Comment by pierre** [comment]
This is still happening on 0.22.25:

```
[WARN] Unable to find Subscription event creation audit log for id XXX
```

**Comment by sbrossie** [comment]
The issue has been identified in the analytics plugin, and a [fix was released](https://github.com/killbill/killbill-analytics-plugin/pull/127), so closing this issue.

**Comment by pierre** [comment]
This is still happening with `7.2.7-4bc554a` unfortunately:

```
Unable to find Subscription event creation audit log for id 070c933d-9d7b-4b65-89c9-c2c6429a7f87
```

**Comment by pierre** [comment]
Unclear if it's related but I came across for a very large account (Kill Bill `0.22.29-8e93f0a319`):
```
Caused by: java.lang.NullPointerException: null
	at org.killbill.billing.util.audit.dao.DefaultAuditDao$3.inTransaction(DefaultAuditDao.java:250)
	at org.killbill.billing.util.audit.dao.DefaultAuditDao$3.inTransaction(DefaultAuditDao.java:245)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:74)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:61)
	at org.skife.jdbi.v2.sqlobject.InTransactionHandler$1.inTransaction(InTransactionHandler.java:41)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:188)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:86)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:62)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:332)
	at org.skife.jdbi.v2.sqlobject.InTransactionHandler.invoke(InTransactionHandler.java:36)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:184)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:97)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$93ec8c0.inTransaction(<generated>)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:98)
	at org.killbill.billing.util.audit.dao.DefaultAuditDao.doGetAuditLogsViaHistoryForId(DefaultAuditDao.java:245)
	at org.killbill.billing.util.audit.dao.DefaultAuditDao.getAuditLogsForId(DefaultAuditDao.java:179)
	at org.killbill.billing.util.audit.api.DefaultAuditUserApi.getAuditLogs(DefaultAuditUserApi.java:87)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:89)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:105)
	at sun.reflect.GeneratedMethodAccessor723.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.killbill.billing.osgi.api.ROOSGIKillbillInterceptor.invoke(ROOSGIKillbillInterceptor.java:59)
	at com.sun.proxy.$Proxy393.getAuditLogs(Unknown Source)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessFactoryBase$3.getAuditLog(BusinessFactoryBase.java:297)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessFactoryBase$AuditLogWithRetry.withRetry(BusinessFactoryBase.java:750)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessFactoryBase.getSubscriptionEventCreationAuditLog(BusinessFactoryBase.java:292)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessContextFactory.getSubscriptionEventCreationAuditLog(BusinessContextFactory.java:403)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.createBusinessSubscriptionTransition(BusinessSubscriptionTransitionFactory.java:208)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.createBusinessSubscriptionTransition(BusinessSubscriptionTransitionFactory.java:170)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.buildTransitionsForBundle(BusinessSubscriptionTransitionFactory.java:117)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.buildTransitionsForBundle(BusinessSubscriptionTransitionFactory.java:89)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.createBusinessSubscriptionTransitions(BusinessSubscriptionTransitionFactory.java:75)
	at org.killbill.billing.plugin.analytics.dao.factory.BusinessSubscriptionTransitionFactory.createBusinessSubscriptionTransitions(BusinessSubscriptionTransitionFactory.java:62)
	at org.killbill.billing.plugin.analytics.dao.BusinessSubscriptionTransitionDao.update(BusinessSubscriptionTransitionDao.java:89)
	at org.killbill.billing.plugin.analytics.dao.AllBusinessObjectsDao.update(AllBusinessObjectsDao.java:58)
	at org.killbill.billing.plugin.analytics.api.user.AnalyticsUserApi.rebuildAnalyticsForAccount(AnalyticsUserApi.java:128)
	at org.killbill.billing.plugin.analytics.http.AnalyticsAccountResource.doPut(AnalyticsAccountResource.java:85)
```
