### ISSUE TITLE
IndexOutOfBoundsException in PaymentAutomatonRunner

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#290]
Triggered a couple of times under high load:

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonDAOHelper.createNewPaymentTransaction(PaymentAutomatonDAOHelper.java:85)
	at org.killbill.billing.payment.core.sm.PaymentLeavingStateCallback.leavingState(PaymentLeavingStateCallback.java:55)
	at org.killbill.automaton.DefaultState.runOperation(DefaultState.java:78)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.runStateMachineOperation(PaymentAutomatonRunner.java:187)
	... 91 common frames omitted
```

**Comment by pierre** [comment]
Unable to reproduce with jDBI 2.60-SNAPSHOT.
