### ISSUE TITLE
jdbi: Query did not have a result set, perhaps you meant update?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#292]
Triggered under high load:

```
2015-03-12 09:08:56,049 [qtp150180729-177] WARN  o.k.b.u.e.d.EntitySqlDaoWrapperInvocationHandler - Error during transaction for sql entity interface org.killbill.billing.payment.dao.PaymentSqlDao and method getById
2015-03-12 09:08:56,080 [qtp150180729-177] WARN  o.k.b.j.mappers.ExceptionMapperBase - Internal error
org.killbill.billing.payment.api.PaymentApiException: Internal payment error : org.skife.jdbi.v2.exceptions.NoResultsException: Query did not have a result set, perhaps you meant update? [statement:"getById", located:"select
  t.record_id
, t.id
, t.account_id
, t.payment_method_id
, t.external_key
, t.state_name
, t.last_success_state_name
, t.created_by
, t.created_date
, t.updated_by
, t.updated_date
, t.record_id as payment_number
, t.account_record_id
, t.tenant_record_id
from payments t
where t.id = :id
and t.tenant_record_id = :tenantRecordId
;", rewritten:"select
  t.record_id
, t.id
, t.account_id
, t.payment_method_id
, t.external_key
, t.state_name
, t.last_success_state_name
, t.created_by
, t.created_date
, t.updated_by
, t.updated_date
, t.record_id as payment_number
, t.account_record_id
, t.tenant_record_id
from payments t
where t.id = ?
and t.tenant_record_id = ?
;", arguments:{ positional:{}, named:{id:'225155f1-7da7-47d6-bdb8-8ab062fa9356',contextUserType:'CUSTOMER',createdBy:'JMeter',userToken:UUIDArgument{value=89186e20-00c1-4325-8415-7f8c4b428c61},updatedDate:DateTimeArgument{value=2015-03-12T16:08:53.000Z},accountRecordId:185175,callOrigin:'EXTERNAL',tenantRecordId:1,class:class org.killbill.billing.callcontext.InternalCallContext,reasonCode:'null',createdDate:DateTimeArgument{value=2015-03-12T16:08:53.000Z},comments:'null',updatedBy:'JMeter'}, finder:[]}]
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.runStateMachineOperation(PaymentAutomatonRunner.java:198)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.run(PaymentAutomatonRunner.java:174)
	at org.killbill.billing.payment.core.PaymentProcessor.performOperation(PaymentProcessor.java:322)
	at org.killbill.billing.payment.core.PaymentProcessor.createPurchase(PaymentProcessor.java:121)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createPurchase(DefaultPaymentApi.java:139)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createPurchaseWithPaymentControl(DefaultPaymentApi.java:148)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.AccountResource.processPayment(AccountResource.java:752)
	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:107)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:66)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.skife.jdbi.v2.exceptions.NoResultsException: Query did not have a result set, perhaps you meant update? [statement:"getById", located:"select
  t.record_id
, t.id
, t.account_id
, t.payment_method_id
, t.external_key
, t.state_name
, t.last_success_state_name
, t.created_by
, t.created_date
, t.updated_by
, t.updated_date
, t.record_id as payment_number
, t.account_record_id
, t.tenant_record_id
from payments t
where t.id = :id
and t.tenant_record_id = :tenantRecordId
;", rewritten:"select
  t.record_id
, t.id
, t.account_id
, t.payment_method_id
, t.external_key
, t.state_name
, t.last_success_state_name
, t.created_by
, t.created_date
, t.updated_by
, t.updated_date
, t.record_id as payment_number
, t.account_record_id
, t.tenant_record_id
from payments t
where t.id = ?
and t.tenant_record_id = ?
;", arguments:{ positional:{}, named:{id:'225155f1-7da7-47d6-bdb8-8ab062fa9356',contextUserType:'CUSTOMER',createdBy:'JMeter',userToken:UUIDArgument{value=89186e20-00c1-4325-8415-7f8c4b428c61},updatedDate:DateTimeArgument{value=2015-03-12T16:08:53.000Z},accountRecordId:185175,callOrigin:'EXTERNAL',tenantRecordId:1,class:class org.killbill.billing.callcontext.InternalCallContext,reasonCode:'null',createdDate:DateTimeArgument{value=2015-03-12T16:08:53.000Z},comments:'null',updatedBy:'JMeter'}, finder:[]}]
	at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:38)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1340)
	at org.skife.jdbi.v2.Query.fold(Query.java:170)
	at org.skife.jdbi.v2.Query.first(Query.java:265)
	at org.skife.jdbi.v2.Query.first(Query.java:257)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$SingleValueResultReturnThing.result(ResultReturnThing.java:111)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:47)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:44)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:171)
	at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$d99b8379.getById(<generated>)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$2.execute(EntitySqlDaoWrapperInvocationHandler.java:203)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeRaw(EntitySqlDaoWrapperInvocationHandler.java:200)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeSafely(EntitySqlDaoWrapperInvocationHandler.java:195)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.access$000(EntitySqlDaoWrapperInvocationHandler.java:81)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$1.execute(EntitySqlDaoWrapperInvocationHandler.java:116)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invoke(EntitySqlDaoWrapperInvocationHandler.java:113)
	at com.sun.proxy.$Proxy189.getById(Unknown Source)
	at org.killbill.billing.payment.dao.DefaultPaymentDao$12.inTransaction(DefaultPaymentDao.java:247)
	at org.killbill.billing.payment.dao.DefaultPaymentDao$12.inTransaction(DefaultPaymentDao.java:240)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:61)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:48)
	at org.skife.jdbi.v2.sqlobject.InTransactionWithIsolationLevelHandler$1.inTransaction(InTransactionWithIsolationLevelHandler.java:37)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:192)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:82)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:61)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:87)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:317)
	at org.skife.jdbi.v2.sqlobject.InTransactionWithIsolationLevelHandler.invoke(InTransactionWithIsolationLevelHandler.java:33)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:171)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:89)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$b84d00c9.inTransaction(<generated>)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:77)
	at org.killbill.billing.payment.dao.DefaultPaymentDao.insertPaymentWithFirstTransaction(DefaultPaymentDao.java:240)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonDAOHelper.createNewPaymentTransaction(PaymentAutomatonDAOHelper.java:84)
	at org.killbill.billing.payment.core.sm.PaymentLeavingStateCallback.leavingState(PaymentLeavingStateCallback.java:55)
	at org.killbill.automaton.DefaultState.runOperation(DefaultState.java:78)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.runStateMachineOperation(PaymentAutomatonRunner.java:187)
	... 91 common frames omitted
```

**Comment by pierre** [comment]
Unable to reproduce with jDBI 2.60-SNAPSHOT.
