### ISSUE TITLE
Got lots of Thread error

### ISSUE THREAD

**Issue by davidx1985** [killbill/killbill#317]
Hi,

I got lots of Thread errors during running killbill web server using jetty-8:

    2015-05-08 16:05:17,831 [TenantExecutor-1] ERROR o.k.c.c.FailsafeScheduledExecutor - Thread[TenantExecutor-1,5,main] ended abnormally with an exception
    java.lang.NullPointerException: null
    	at org.killbill.billing.tenant.api.TenantCacheInvalidation$TenantCacheInvalidationRunnable.run(TenantCacheInvalidation.java:174) ~[killbill-tenant-0.13.5.jar:na]
    	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40) ~[killbill-concurrent-0.2.33.jar:na]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
    	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

My environment is java 1.8, jetty-8 and killbill 0.13.5.

Any idea?

**Comment by davidx1985** [comment]
I just tried using killbill-concurrent-0.3.jar, same issue

**Comment by pierre** [comment]
Is your database up-to-date (see the [migration guide](https://github.com/killbill/killbill/wiki/Kill-Bill-Migration-0.12.x-to-0.14.x))?

**Comment by davidx1985** [comment]
thank you for your reply, but this doc is about migration from 0.12.x to 0.14.x, and I am using 0.13.x, should I still follow it?

**Comment by pierre** [comment]
The 0.13.1 DDL won't work for 0.13.5.

0.13.x is a development release train leading to 0.14.x. As such, the APIs and DDL are constantly evolving and updates are posted on that migration guide.

FYI, 0.13.7 has just been released and should become 0.14.0-final.

**Comment by davidx1985** [comment]
Oh, in that way, should I upgrade it to 0.13.7 and use 0.14.x database?

BTW, we should have a full sql script for 0.14.x, :-)

**Comment by davidx1985** [comment]
@pierre Same issue, could you spend some time on this, thanks!

**Comment by pierre** [comment]
> BTW, we should have a full sql script for 0.14.x, :-)

Yes, stable (even) versions have full documentation.

**Comment by davidx1985** [comment]
I think we close this issue now.
