### ISSUE TITLE
Unable to start bundle

### ISSUE THREAD

**Issue by david-xie** [killbill/killbill#318]
Error message:

    2015-05-09 00:12:24,565 [main] INFO  o.killbill.billing.osgi.FileInstall - Starting bundle file:/Users/davidx/Projects/jetty-8/tmp/bundles/platform/jruby.jar
    JRuby bundle activated
    2015-05-09 00:12:24,597 [main] WARN  o.killbill.billing.osgi.FileInstall - Unable to start bundle
    org.osgi.framework.BundleException: Activator start error in bundle org.kill-bill.billing.killbill-platform-osgi-bundles-jruby [1].
      at org.apache.felix.framework.Felix.activateBundle(Felix.java:2204)
      at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
      at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
      at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
      at org.killbill.billing.osgi.FileInstall.startBundle(FileInstall.java:202)
      at org.killbill.billing.osgi.FileInstall.startBundles(FileInstall.java:94)
      at org.killbill.billing.osgi.DefaultOSGIService.start(DefaultOSGIService.java:94)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at org.killbill.billing.lifecycle.DefaultLifecycle.doFireStage(DefaultLifecycle.java:150)
      at org.killbill.billing.lifecycle.DefaultLifecycle.fireSequence(DefaultLifecycle.java:137)
      at org.killbill.billing.lifecycle.DefaultLifecycle.fireStartupSequencePriorEventRegistration(DefaultLifecycle.java:78)
      at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.startLifecycle(KillbillPlatformGuiceListener.java:232)
      at org.killbill.billing.server.listeners.KillbillPlatformGuiceListener.contextInitialized(KillbillPlatformGuiceListener.java:105)
      at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
      at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
      at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
      at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
      at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
      at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
      at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
      at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:39)
      at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
      at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:494)
      at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:141)
      at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:145)
      at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:56)
      at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:615)
      at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:540)
      at org.eclipse.jetty.util.Scanner.scan(Scanner.java:403)
      at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:337)
      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
      at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:121)
      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
      at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:555)
      at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:230)
      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
      at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81)
      at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58)
      at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96)
      at org.eclipse.jetty.server.Server.doStart(Server.java:282)
      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
      at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1274)
      at java.security.AccessController.doPrivileged(Native Method)
      at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1197)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at org.eclipse.jetty.start.Main.invokeMain(Main.java:473)
      at org.eclipse.jetty.start.Main.start(Main.java:615)
      at org.eclipse.jetty.start.Main.main(Main.java:96)
    Caused by: java.lang.NullPointerException: null
      at org.killbill.billing.osgi.bundles.jruby.JRubyActivator$2.doCall(JRubyActivator.java:91)
      at org.killbill.billing.osgi.bundles.jruby.JRubyActivator.withContextClassLoader(JRubyActivator.java:236)
      at org.killbill.billing.osgi.bundles.jruby.JRubyActivator.startWithContextClassLoader(JRubyActivator.java:81)
      at org.killbill.billing.osgi.bundles.jruby.JRubyActivator.access$000(JRubyActivator.java:46)
      at org.killbill.billing.osgi.bundles.jruby.JRubyActivator$1.isRegistered(JRubyActivator.java:69)
      at org.killbill.killbill.osgi.libs.killbill.KillbillServiceListener.serviceChanged(KillbillServiceListener.java:66)
      at org.killbill.killbill.osgi.libs.killbill.KillbillServiceListener.listenForService(KillbillServiceListener.java:40)
      at org.killbill.billing.osgi.bundles.jruby.JRubyActivator.start(JRubyActivator.java:72)
      at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
      at org.apache.felix.framework.Felix.activateBundle(Felix.java:2154)
      ... 54 common frames omitted

killbill 0.13.7, jetty 8 and java 1.8

**Comment by davidx1985** [comment]
Also, I am using jruby 0.1.4

**Comment by kares** [comment]
seems that you've been using a development KB version ... you should either go back to 0.12 or use 0.14

**Comment by davidx1985** [comment]
I will use 0.14 then

**Comment by david-xie** [comment]
I don't have this issue since 0.14. close it now
