### ISSUE TITLE
NPE in PendingTransactionTask

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#319]
Maybe related to #230?

```
2015-05-13 05:44:37,048 [PaymentJanitor-1] ERROR o.k.c.c.FailsafeScheduledExecutor - Thread[PaymentJanitor-1,5,main] ended abnormally with an exception
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:52)
	at com.google.common.base.Objects.firstNonNull(Objects.java:186)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$6.execute(EntitySqlDaoWrapperInvocationHandler.java:374)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.updateHistoryAndAudit(EntitySqlDaoWrapperInvocationHandler.java:369)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeWithAuditAndHistory(EntitySqlDaoWrapperInvocationHandler.java:336)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeSafely(EntitySqlDaoWrapperInvocationHandler.java:191)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.access$000(EntitySqlDaoWrapperInvocationHandler.java:81)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$1.execute(EntitySqlDaoWrapperInvocationHandler.java:116)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invoke(EntitySqlDaoWrapperInvocationHandler.java:113)
	at com.sun.proxy.$Proxy213.failOldPendingTransactions(Unknown Source)
	at org.killbill.billing.payment.dao.DefaultPaymentDao$7.inTransaction(DefaultPaymentDao.java:170)
	at org.killbill.billing.payment.dao.DefaultPaymentDao$7.inTransaction(DefaultPaymentDao.java:156)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:61)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:48)
	at org.skife.jdbi.v2.sqlobject.InTransactionWithIsolationLevelHandler$1.inTransaction(InTransactionWithIsolationLevelHandler.java:39)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:82)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:61)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:87)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:339)
	at org.skife.jdbi.v2.sqlobject.InTransactionWithIsolationLevelHandler.invoke(InTransactionWithIsolationLevelHandler.java:34)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:175)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:92)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$80b630a5.inTransaction(<generated>)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:77)
	at org.killbill.billing.payment.dao.DefaultPaymentDao.failOldPendingTransactions(DefaultPaymentDao.java:156)
	at org.killbill.billing.payment.core.janitor.PendingTransactionTask.doIteration(PendingTransactionTask.java:60)
	at org.killbill.billing.payment.core.janitor.PendingTransactionTask.doIteration(PendingTransactionTask.java:39)
	at org.killbill.billing.payment.core.janitor.CompletionTaskBase.run(CompletionTaskBase.java:95)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbrossie** [comment]
This is a DUP of #230
