### ISSUE TITLE
Performance regression generating UUIDs

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#344]
After https://github.com/killbill/killbill/issues/323, the generation of UUIDs has become really slow in low entropy environments (including the Docker image).

A typical stack trace is:

```
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:551)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:139)
	at sun.security.provider.SecureRandom.engineGenerateSeed(SecureRandom.java:136)
	at java.security.SecureRandom.generateSeed(SecureRandom.java:517)
	at org.killbill.billing.util.UUIDs$LightSecureRandom.<init>(UUIDs.java:151)
	at org.killbill.billing.util.UUIDs$1.initialValue(UUIDs.java:75)
	at org.killbill.billing.util.UUIDs$1.initialValue(UUIDs.java:73)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
	at java.lang.ThreadLocal.get(ThreadLocal.java:150)
	at org.killbill.billing.util.UUIDs.rndUUIDv4(UUIDs.java:40)
	at org.killbill.billing.util.UUIDs.randomUUID(UUIDs.java:36)
	at org.killbill.billing.jaxrs.util.Context.createContext(Context.java:51)
```

Even Tomcat warns us:

```
o.a.catalina.util.SessionIdGenerator - Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [54,034] milliseconds.
```

**Comment by pierre** [comment]
Here is the Tomcat trace:

```
"localhost-startStop-1" daemon prio=10 tid=0x00007f88b0002800 nid=0x3d runnable [0x00007f88c0441000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:551)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:139)
	at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:197)
	at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:214)
	- locked <0x00000007456c7ac0> (a sun.security.provider.SecureRandom)
	at java.security.SecureRandom.nextBytes(SecureRandom.java:455)
	- locked <0x00000007456c7dd8> (a java.security.SecureRandom)
	at java.security.SecureRandom.next(SecureRandom.java:477)
	at java.util.Random.nextInt(Random.java:239)
	at org.apache.catalina.util.SessionIdGenerator.createSecureRandom(SessionIdGenerator.java:246)
	at org.apache.catalina.util.SessionIdGenerator.getRandomBytes(SessionIdGenerator.java:183)
	at org.apache.catalina.util.SessionIdGenerator.generateSessionId(SessionIdGenerator.java:153)
	at org.apache.catalina.session.ManagerBase.startInternal(ManagerBase.java:573)
```

**Comment by pierre** [comment]
Setting `-Djava.security.egd=file:/dev/./urandom` in the `jvm:` line in the `kpm.yml` (instead of `properties:`, which are evaluated later) solves the issue.

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-cloud/commit/e21a87bf1cc4ae337cff9ee74815f5d004833eec.
