### ISSUE TITLE
Janitor: wiring issue in Beatrix

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#355]
Seen the following exception while running tests:

```
Caused by: org.killbill.notificationq.api.NotificationQueueService$NotificationQueueAlreadyExists: Queue for svc payment-service and name janitor already exist
	at org.killbill.notificationq.NotificationQueueServiceBase.createNotificationQueue(NotificationQueueServiceBase.java:50)
	at org.killbill.billing.payment.core.janitor.Janitor.initialize(Janitor.java:76)
	at org.killbill.billing.payment.glue.DefaultPaymentService.initialize(DefaultPaymentService.java:79)
```

**Comment by sbrossie** [comment]
The direct issue is that the janitor is [not restartable](https://github.com/killbill/killbill/blob/killbill-0.15.2/payment/src/main/java/org/killbill/billing/payment/core/janitor/Janitor.java#L98).

Since we call start/stop in between each tests, the start bails out early and the stop goes through and we see the following:
'Janitor is not a restartable service, and was already started, aborting' (start aborting early)
'Queue for svc payment-service and name janitor already exist' (stop being without start)

**Comment by sbrossie** [comment]
The wider issue has to do with `Executors`. Executor are not restartable (that is there is no start method, and after we ran `shutdownNow`, nothing can be done. Since most of our executors are injected, there is nothing we can do.

A solution is to do the same we did for the `notificationQ`,`PersistentBus`, which is to recreate instances at start sequence and call `shutdownNow` during stop sequence.

**Comment by sbrossie** [comment]
Note that we have a similar issue with the executor from the tenant module.
