### ISSUE TITLE
Investigate test failure on EC2 build machine

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#365]
```
[main] WARN org.killbill.billing.lifecycle.DefaultLifecycle - Failed to inject org.killbill.billing.platform.api.OSGIService
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - *** Starting test org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi:testAuditLogsForEntitlementAndSubscriptionBaseObjects
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO org.killbill.clock.ClockMock -             ************      ADJUSTING CLOCK FROM 2015-08-10T18:57:12.000Z to 2012-05-07T00:03:42.000Z     ********************
[main] INFO org.killbill.queue.DBBackedQueue - DBBackedQueue-bus-bus_events: Initialized with useInflightQueue = false, queueId = 12, isSticky = false, isQueueOpenForWrite = false, isQueueOpenForRead = false
[main] INFO org.killbill.queue.DefaultQueueLifecycle - Bus: Starting with 1 threads
[bus_events-th] INFO org.killbill.queue.DefaultQueueLifecycle - Bus: Thread bus_events-th [128] starting
[main] INFO org.killbill.queue.DefaultQueueLifecycle - Bus: Done waiting for all threads to be started, got 1/1
[main] INFO org.killbill.queue.DefaultQueueLifecycle - NotificationQ: Starting with 1 threads
[notifications-th] INFO org.killbill.queue.DefaultQueueLifecycle - NotificationQ: Thread notifications-th [129] starting
[main] INFO org.killbill.queue.DefaultQueueLifecycle - NotificationQ: Done waiting for all threads to be started, got 1/1
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-130: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-131: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-132: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-133: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-134: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-135: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-136: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-137: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-138: starting...
[notifications-th] INFO org.killbill.notificationq.NotificationQueueDispatcher - NotificationRunner notifications-th-139: starting...
[main] INFO org.killbill.xmlloader.XMLLoader - Initializing an object of class org.killbill.billing.catalog.StandaloneCatalog from xml file at: jar:file:/var/lib/killbill/killbill/catalog/target/killbill-catalog-0.15.2-SNAPSHOT-tests.jar!/catalogTest.xml
[main] INFO org.killbill.xmlloader.XMLLoader - Errors: 0 for jar:file:/var/lib/killbill/killbill/catalog/target/killbill-catalog-0.15.2-SNAPSHOT-tests.jar!/catalogTest.xml
[main] INFO org.killbill.billing.catalog.DefaultCatalogService - Successfully loaded the default catalog catalogTest.xml
[main] INFO org.killbill.clock.ClockMock -             ************      ADJUSTING CLOCK FROM 2012-05-07T00:03:43.000Z to 2013-08-07T00:00:00.000Z     ********************
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got subscription event DefaultEffectiveSubscriptionEvent{bundleId=e0da67d5-e0de-4dc3-b6dc-92c24213a310, totalOrdering=0, subscriptionId=0f6e88b1-92d8-4ba5-abec-41050b9d593b, eventId=83e01511-581a-4ceb-9a13-ea796dd2ffd2, requestedTransitionTime=2013-08-07T00:00:00.000Z, effectiveTransitionTime=2013-08-07T00:00:00.000Z, previousState=null, previousPriceList='null', previousPlan='null', previousPhase='null', nextState=ACTIVE, nextPriceList='DEFAULT', nextPlan='shotgun-annual', nextPhase='shotgun-annual-trial', remainingEventsForUserOperation=0, transitionType=CREATE, startDate=2013-08-07T00:00:00.000Z}
[main] INFO org.killbill.clock.ClockMock -             ************      ADJUSTING CLOCK FROM 2013-08-07T00:00:00.000Z to 2013-09-07T00:00:00.000Z     ********************
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got subscription event DefaultEffectiveSubscriptionEvent{bundleId=e0da67d5-e0de-4dc3-b6dc-92c24213a310, totalOrdering=2, subscriptionId=0f6e88b1-92d8-4ba5-abec-41050b9d593b, eventId=9d17e080-9006-4eed-947d-3a66895b6ba0, requestedTransitionTime=2013-08-07T00:00:00.000Z, effectiveTransitionTime=2013-09-06T00:00:00.000Z, previousState=ACTIVE, previousPriceList='DEFAULT', previousPlan='shotgun-annual', previousPhase='shotgun-annual-trial', nextState=ACTIVE, nextPriceList='DEFAULT', nextPlan='shotgun-annual', nextPhase='shotgun-annual-evergreen', remainingEventsForUserOperation=0, transitionType=PHASE, startDate=2013-08-07T00:00:00.000Z}
[main] INFO org.killbill.clock.ClockMock -             ************      ADJUSTING CLOCK FROM 2013-09-07T00:00:15.000Z to 2013-12-28T00:00:00.000Z     ********************
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got entitlement event DefaultBlockingTransitionInternalEvent{blockableId=e0da67d5-e0de-4dc3-b6dc-92c24213a310, blockingType=SUBSCRIPTION_BUNDLE, isTransitionedToBlockedBilling=true, isTransitionedToUnblockedBilling=false, isTransitionedToBlockedEntitlement=true, isTransitionedToUnblockedEntitlement=false}
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got entitlement event DefaultEffectiveEntitlementEvent{id=a433a3aa-68eb-42ae-aba1-cb1accd947b2, entitlementId=0f6e88b1-92d8-4ba5-abec-41050b9d593b, bundleId=e0da67d5-e0de-4dc3-b6dc-92c24213a310, accountId=b487333f-9b34-4db6-b26c-82278a5b262a, transitionType=BLOCK_BUNDLE, effectiveTransitionTime=2013-09-17T00:00:00.000Z, requestedTransitionTime=2013-12-28T00:00:00.000Z}
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got entitlement event DefaultBlockingTransitionInternalEvent{blockableId=e0da67d5-e0de-4dc3-b6dc-92c24213a310, blockingType=SUBSCRIPTION_BUNDLE, isTransitionedToBlockedBilling=false, isTransitionedToUnblockedBilling=true, isTransitionedToBlockedEntitlement=false, isTransitionedToUnblockedEntitlement=true}
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got entitlement event DefaultEffectiveEntitlementEvent{id=9e009ff6-2679-4ab8-9d9d-afcd02a73125, entitlementId=0f6e88b1-92d8-4ba5-abec-41050b9d593b, bundleId=e0da67d5-e0de-4dc3-b6dc-92c24213a310, accountId=b487333f-9b34-4db6-b26c-82278a5b262a, transitionType=UNBLOCK_BUNDLE, effectiveTransitionTime=2013-12-24T00:00:00.000Z, requestedTransitionTime=2013-12-28T00:00:22.000Z}
[main] ERROR org.killbill.billing.api.TestApiListener - TestApiListener did not complete in 25000 ms, remaining events are CANCEL BLOCK
[bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got entitlement event DefaultBlockingTransitionInternalEvent{blockableId=0f6e88b1-92d8-4ba5-abec-41050b9d593b, blockingType=SUBSCRIPTION, isTransitionedToBlockedBilling=false, isTransitionedToUnblockedBilling=false, isTransitionedToBlockedEntitlement=false, isTransitionedToUnblockedEntitlement=false}
[main] ERROR org.killbill.billing.api.TestApiListener - TestApiListener did not complete in 25000 ms, remaining events are CANCEL
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi:testAuditLogsForEntitlementAndSubscriptionBaseObjects !!! FAILURE !!! (41 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi:testBlockingStatesInTimelineApi !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi:testWithMultipleBundle !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testCancelBundleBeforeSubscription !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testOneEntitlementNoBlockingStates !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testOneEntitlementWithBlockingStatesSubscription !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testOneEntitlementWithInitialBlockingState !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testOneEntitlementWithOverduePauseThenCancel !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testOneEntitlementWithPauseResume !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnCorrectOrder !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnInvalidOrder1 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnInvalidOrder2 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnInvalidOrder3 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnInvalidOrderAndDifferentSubscriptionsDates !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnInvalidOrderAndDifferentSubscriptionsSameDates1 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testReOrderSubscriptionEventsOnInvalidOrderAndDifferentSubscriptionsSameDates2 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testRemoveOverlappingBlockingStates !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testVariousBlockingStatesAtTheSameEffectiveDate !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testWithMultipleEntitlements !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestDefaultSubscriptionBundleTimeline:testWithOverdueOffline !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestEntitlementDateHelper:testIsBeforeOrEqualsToday !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestEntitlementDateHelper:testWhereLocalDateInAccountTimeZoneContainsNow !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestEntitlementDateHelper:testWithAccountInUtc !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestEntitlementDateHelper:testWithAccountInUtcMinus8 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestEntitlementDateHelper:testWithAccountInUtcPlus5 !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testCancelAddonsWhenBaseEntitlementIsCancelled !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testCancellationBaseEOTAddOnIMM !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testCancellationBillingIMMEntitlementEOT !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testCancellationEOT !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testCancellationIMM !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testCancellationIMMBillingEOT !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testChangePlanEOT !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testChangePlanEOTWith2AddOns !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.engine.core.TestEntitlementUtils:testChangePlanIMM !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***************************************************************************************************
[main] INFO KillbillTestSuite - ***   Ending test org.killbill.billing.entitlement.api.TestEventJson:testDefaultBlockingTransitionInternalEvent !!! FAILURE !!! (0 s.)
[main] INFO KillbillTestSuite - ***************************************************************************************************
Tests run: 171, Failures: 2, Errors: 0, Skipped: 146, Time elapsed: 115.764 sec <<< FAILURE!
testAuditLogsForEntitlementAndSubscriptionBaseObjects(org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi)  Time elapsed: 41.116 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.killbill.billing.api.TestApiListener.assertListenerStatus(TestApiListener.java:81)
	at org.killbill.billing.entitlement.EntitlementTestSuiteWithEmbeddedDB.assertListenerStatus(EntitlementTestSuiteWithEmbeddedDB.java:239)
	at org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi.testAuditLogsForEntitlementAndSubscriptionBaseObjects(TestDefaultSubscriptionApi.java:228)

afterMethod(org.killbill.billing.entitlement.api.TestDefaultSubscriptionApi)  Time elapsed: 66.124 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.killbill.billing.api.TestApiListener.assertListenerStatus(TestApiListener.java:81)
	at org.killbill.billing.entitlement.EntitlementTestSuiteWithEmbeddedDB.assertListenerStatus(EntitlementTestSuiteWithEmbeddedDB.java:239)
	at org.killbill.billing.entitlement.EntitlementTestSuiteWithEmbeddedDB.afterMethod(EntitlementTestSuiteWithEmbeddedDB.java:135)
	at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:189)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:105)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)


Results :

Failed tests: 
  TestDefaultSubscriptionApi.testAuditLogsForEntitlementAndSubscriptionBaseObjects:228->EntitlementTestSuiteWithEmbeddedDB.assertListenerStatus:239 expected [true] but found [false]
  TestDefaultSubscriptionApi>EntitlementTestSuiteWithEmbeddedDB.afterMethod:135->EntitlementTestSuiteWithEmbeddedDB.assertListenerStatus:239 expected [true] but found [false]

Tests run: 171, Failures: 2, Errors: 0, Skipped: 146

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] killbill ........................................... SUCCESS [  2.655 s]
[INFO] killbill-api ....................................... SUCCESS [  1.891 s]
[INFO] killbill-util ...................................... SUCCESS [ 48.894 s]
[INFO] killbill-account ................................... SUCCESS [ 19.607 s]
[INFO] killbill-catalog ................................... SUCCESS [ 25.141 s]
[INFO] killbill-currency .................................. SUCCESS [  0.125 s]
[INFO] killbill-subscription .............................. SUCCESS [05:05 min]
[INFO] killbill-entitlement ............................... FAILURE [01:56 min]
[INFO] killbill-usage ..................................... SKIPPED
[INFO] killbill-invoice ................................... SKIPPED
[INFO] killbill-junction .................................. SKIPPED
[INFO] killbill-overdue ................................... SKIPPED
[INFO] killbill-payment ................................... SKIPPED
[INFO] killbill-tenant .................................... SKIPPED
[INFO] killbill-beatrix ................................... SKIPPED
[INFO] killbill-jaxrs ..................................... SKIPPED
[INFO] killbill-profiles .................................. SKIPPED
[INFO] killbill-profiles-killbill ......................... SKIPPED
[INFO] killbill-profiles-killpay .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:41 min
[INFO] Finished at: 2015-08-10T18:58:19+00:00
[INFO] Final Memory: 54M/480M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.13:test (default-test) on project killbill-entitlement: There are test failures.
[ERROR] 
[ERROR] Please refer to /var/lib/killbill/killbill/entitlement/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :killbill-entitlement
```

**Comment by pierre** [comment]
The root cause is a timing issue due to missing entropy:

```
"notifications-th" prio=10 tid=XXX nid=YYY runnable [ZZZ]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:551)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:139)
	at sun.security.provider.SecureRandom.engineGenerateSeed(SecureRandom.java:136)
	at java.security.SecureRandom.generateSeed(SecureRandom.java:517)
	at org.killbill.billing.util.UUIDs$LightSecureRandom.<init>(UUIDs.java:134)
	at org.killbill.billing.util.UUIDs$1.initialValue(UUIDs.java:70)
	at org.killbill.billing.util.UUIDs$1.initialValue(UUIDs.java:68)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
	at java.lang.ThreadLocal.get(ThreadLocal.java:150)
	at org.killbill.billing.util.UUIDs.rndUUIDv4(UUIDs.java:35)
	at org.killbill.billing.util.UUIDs.randomUUID(UUIDs.java:31)
	at org.killbill.billing.entity.EntityBase.<init>(EntityBase.java:39)
	at org.killbill.billing.util.entity.dao.EntityModelDaoBase.<init>(EntityModelDaoBase.java:35)
	at org.killbill.billing.subscription.engine.dao.model.SubscriptionEventModelDao.<init>(SubscriptionEventModelDao.java:59)
```

**Comment by pierre** [comment]
Launching maven with `-Djava.security.egd=file:/dev/.urandom` on the command line (e.g. `mvn -Djava.security.egd=file:/dev/.urandom clean install -Pmysql`) seems to help, although some other tests are failing too (`org.killbill.billing.payment.api.TestExternalPaymentPlugin:testGetPaymentInfoWithAndWithoutPluginInfo`, other timing issue).

Note that setting the property in other places (`MAVEN_OPTS`, `$JAVA_HOME/jre/lib/security/java.security`, etc.) doesn't seem to help.

**Comment by pierre** [comment]
All tests are now passing when running `mvn -Djava.security.egd=file:/dev/.urandom clean install -Pmysql`.

I'll run a few more iterations just to be safe.
