### ISSUE TITLE
Better exception logging for dispatchWithExceptionHandling

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#390]
Currently, when a payment control plugin times-out, we get the following stack trace:

```
2015-09-01 17:50:28,973 [qtp356308667-22] WARN  o.k.b.p.c.s.c.OperationControlCallback - RetryOperationCallback call TIMEOUT for account XXX
2015-09-01 17:50:28,989 [qtp356308667-22] WARN  o.k.b.j.mappers.ExceptionMapperBase - Internal error
org.killbill.billing.payment.api.PaymentApiException: Internal payment error : java.util.concurrent.TimeoutException
	at org.killbill.billing.payment.core.sm.PluginControlPaymentAutomatonRunner.run(PluginControlPaymentAutomatonRunner.java:128)
	at org.killbill.billing.payment.core.sm.PluginControlPaymentAutomatonRunner.run(PluginControlPaymentAutomatonRunner.java:99)
	at org.killbill.billing.payment.core.PluginControlPaymentProcessor.createAuthorization(PluginControlPaymentProcessor.java:83)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createAuthorizationWithPaymentControl(DefaultPaymentApi.java:109)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.PaymentResource.createComboPayment(PaymentResource.java:643)
	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:110)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:66)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:104)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.killbill.billing.payment.dispatcher.PluginDispatcher.dispatchWithTimeout(PluginDispatcher.java:60)
	at org.killbill.billing.payment.dispatcher.PluginDispatcher.dispatchWithTimeout(PluginDispatcher.java:48)
	at org.killbill.billing.payment.core.sm.OperationCallbackBase.dispatchWithAccountLockAndTimeout(OperationCallbackBase.java:65)
	at org.killbill.billing.payment.core.sm.control.OperationControlCallback.doOperationCallback(OperationControlCallback.java:80)
	at org.killbill.automaton.DefaultOperation.run(DefaultOperation.java:51)
	at org.killbill.automaton.DefaultState.runOperation(DefaultState.java:80)
	at org.killbill.billing.payment.core.sm.PluginControlPaymentAutomatonRunner.run(PluginControlPaymentAutomatonRunner.java:118)
	... 78 common frames omitted
```

The trace isn't really useful. In particular, it doesn't tell which operation timed-out, which makes things difficult to debug (especially if several control plugins are involved).

Adding more information isn't straightforward, because the `Callable` passed to the `PluginDispatcher` is opaque (it may call several plugins). That being said, `PluginDispatcher#dispatchWithTimeout` is called from two places only: `ProcessorBase#dispatchWithExceptionHandling` and `OperationCallbackBase#dispatchWithAccountLockAndTimeout`.

The former use-case is probably the easiest to fix, as it is used outside the state machine and for mono-plugin calls: `buildFormDescriptor`, `processNotification` and `addPaymentMethod`. In all these cases, we first retrieve the plugin (via `getPaymentPluginApi`) and then execute the call. Retrieving the plugin is a cheap operation, that actually doesn't involve the plugin itself. We could move these calls outside the `Callable` and pass the plugin name to `ProcessorBase#dispatchWithExceptionHandling`. When catching the `TimeoutException`, we can now pass a proper message instead of `null` (we could mention the plugin name as well as the `org.killbill.payment.plugin.timeout` property).
Note: we should also fix the `PAYMENT_PLUGIN_TIMEOUT` error code as the message still refers to an invoice (legacy code).

The second use-case is more difficult and there are several cases to look at. `OperationCallbackBase#dispatchWithAccountLockAndTimeout` is called from several places:

* `PaymentOperation#doOperationCallbackWithDispatchAndAccountLock`: this is called for payment operations in the non-controlled state machine and is identical to the first use-case above (single plugin operation). Because the plugin is retrieved in `PaymentOperation#doOperationCallback`, we can do something similar (pass more information to `OperationCallbackBase#dispatchWithAccountLockAndTimeout` to update the exception message)
* `OperationControlCallback#doOperationCallback`: this is called for payment operations in the controlled state machine. This is the most difficult code-path to fix as several plugins are called in the `Callable` (see `executePluginPriorCalls`, `executePluginOnSuccessCalls`, etc.). At the minimum, we could pass the full list of control plugin names (`paymentStateControlContext.getPaymentControlPluginNames()`) to `OperationCallbackBase#dispatchWithAccountLockAndTimeout` for the exception message. We won't know which plugin timed-out, but at least the message will be a bit less cryptic. I'm not sure if there is a better way of getting more information? Note that at this point we don't have yet the actual (non-control) plugin name for the payment operation (it will be looked-up by the non-controlled state machine, when it is called via `OperationControlCallback#doCallSpecificOperationCallback`. We could maybe look it up though since we have access to `paymentStateContext.getPaymentMethodId()`.
* `CompletionControlOperation#doOperationCallback`: this is part of the Janitor (to fix inconsistent states). Only `executePluginOnSuccessCalls` is called here, so it should be similar to the previous use-case.

cc/ @holkra who volunteered to fix this :-)

**Comment by sbrossie** [comment]
+1.

However, if this proves too difficult, a cheaper way would be always log which plugin is called prior making plugin api call (along with `threadId` and `RequestId`), which would then help to reconcile with the TIMEOUT stack trace when that happens.

**Comment by pierre** [comment]
> However, if this proves too difficult, a cheaper way would be always log which plugin is called prior making plugin api call (along with threadId and RequestId), which would then help to reconcile with the TIMEOUT stack trace when that happens.

I originally wanted to stay away from adding logging, as I was afraid it would be too much (messages would be outputted for each payment call), but I'm now reconsidering it.

Aber das eine braucht das andere nicht auszuschließen: we could do both (i.e. the proposed fix and adding logging), the logging information around each plugin call would be a cheap way of solving the hard case above (`OperationControlCallback#doOperationCallback`). We would also have timing/performance information and could report on it.
