### ISSUE TITLE
Enhance logging of failed payment retries

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#394]
Currently, the stack trace looks like:

```
2015-09-05 16:30:16,024 [Thread-21] WARN  o.k.b.k.0.4.0.SNAPSHOT - [cybersource-plugin] Unsuccessful purchase: One or more fields contains invalid data
2015-09-05 16:30:16,046 [Thread-21] INFO  o.k.b.p.j.a.1.0.2.SNAPSHOT - Refreshing Analytics data for account XXX
2015-09-05 16:30:16,047 [notifications-th] WARN  o.k.b.payment.core.ProcessorBase - Failed to retry attempt YYY for plugins (__INVOICE_PAYMENT_CONTROL_PLUGIN__)
org.killbill.billing.payment.api.PaymentApiException: Internal payment error :
        at org.killbill.billing.payment.core.sm.PluginControlPaymentAutomatonRunner.run(PluginControlPaymentAutomatonRunner.java:126)
        at org.killbill.billing.payment.core.PluginControlPaymentProcessor.retryPaymentTransaction(PluginControlPaymentProcessor.java:208)
        at org.killbill.billing.payment.retry.DefaultRetryService.retryPaymentTransaction(DefaultRetryService.java:49)
        at org.killbill.billing.payment.retry.BaseRetryService$1.handleReadyNotification(BaseRetryService.java:74)
        at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)
        at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
        at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
        at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:102)
        at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:85)
        at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.killbill.automaton.OperationException: null
        at org.killbill.billing.payment.core.sm.control.OperationControlCallback$1.doOperation(OperationControlCallback.java:141)
        at org.killbill.billing.payment.core.sm.control.OperationControlCallback$1.doOperation(OperationControlCallback.java:82)
        at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:198)
        at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:181)
        at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:162)
        at org.killbill.billing.payment.dispatcher.CallableWithRequestData.call(CallableWithRequestData.java:39)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
```

Logging the full trace doesn't seem useful. It would be nice to log something like:

```
Failed to retry attempt YYY (__INVOICE_PAYMENT_CONTROL_PLUGIN__), retrying at 2015-09-06 16:30:16,047
```

Also, `PluginControlPaymentProcessor` shouldn't use the logger from `ProcessorBase`, as it makes this log line confusing:

```
WARN  o.k.b.payment.core.ProcessorBase - Failed to retry attempt YYY (__INVOICE_PAYMENT_CONTROL_PLUGIN__)
```

**Comment by sbrossie** [comment]
Regarding the stack trace, do we want to keep the stack trace?

Regarding logging the next retry date, why not but this info is *not* available from `DefaultRetryService` and not even from `PluginControlPaymentProcessor`. However it is available from the [PluginControlPaymentAutomatonRunner](https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/core/sm/PluginControlPaymentAutomatonRunner.java#L126) since we have access to the payment control context where that date should be set. So if we really want to log that from `DefaultRetryService` or `PluginControlPaymentProcessor`, we have to make some significant changes.

**Comment by pierre** [comment]
> Regarding the stack trace, do we want to keep the stack trace?

Probably not (whenever we log things like `Caused by: org.killbill.automaton.OperationException: null`, it's rarely useful).

> Regarding logging the next retry date, why not but this info is not available from `DefaultRetryService` and not even from `PluginControlPaymentProcessor`

Similar to https://github.com/killbill/killbill/issues/393, I think it's a nice to have, but if it's too hard, it's probably not worth it (maybe we could log it when inserting the notification entry?). Fixing the logger name and removing the stack trace would be useful already.

**Comment by sbrossie** [comment]
> Fixing the logger name 
Because we are using the logger from a parent class.

**Comment by pierre** [comment]
Fixed in enhanced-logging branch.
