### ISSUE TITLE
Set default account timezone if unspecified

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#396]
The account timezone is currently defined as:

```
time_zone` varchar(50) COLLATE utf8_bin DEFAULT NULL
```

However, the code pretty much always assumes one is set. For instance, creating a new base subscription won't work if it's null:

```
java.lang.NullPointerException: null
	at org.killbill.clock.ClockUtil.computeDateTimeWithUTCReferenceTime(ClockUtil.java:51)
	at org.killbill.billing.entitlement.api.EntitlementDateHelper.fromLocalDateAndReferenceTime(EntitlementDateHelper.java:44)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi$1.doCall(DefaultEntitlementApi.java:149)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi$1.doCall(DefaultEntitlementApi.java:136)
	at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:60)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi.createBaseEntitlement(DefaultEntitlementApi.java:160)
	
```

We should probably change the constraint on the table and set a default value (UTC) at account creation time.

**Comment by vp-maguero** [comment]
I'm helping to resolve this issue.
I added a default "UTC" value to the account.time_zone column as you suggested, but it still saving **null** when there is no value for this property in the create account request.
It seems is something related with MySql Strict mode (https://dev.mysql.com/doc/refman/5.0/en/data-type-defaults.html).

```
time_zone varchar(50) DEFAULT 'UTC'   // (still get NULL saved into this column)
```

```
time_zone varchar(50) NOT NULL DEFAULT 'UTC' 
java.sql.SQLIntegrityConstraintViolationException: Column 'time_zone' cannot be null"
```

Any thoughts?

**Comment by pierre** [comment]
I would actually set the default in the code (similar to how we set the [external key](https://github.com/killbill/killbill/blob/master/account/src/main/java/org/killbill/billing/account/dao/AccountModelDao.java#L70)) and simply add a `NOT NULL` constraint in the database.

**Comment by vp-maguero** [comment]
Thank you.
This is done and a new pull request was created.
https://github.com/killbill/killbill/pull/402

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill/commit/15d0e363d65e46d8814350e0860573abb790862d.
