### ISSUE TITLE
Junction BCD refactoring

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#56]

**Comment by sbrossie** [comment]
@pierre Could you provide more details?

**Comment by pierre** [comment]
This ticket is mainly to simplify [BillCycleDayCalculator](https://github.com/killbill/killbill/blob/master/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BillCycleDayCalculator.java):

* The invocation of the catalog APIs are quite tricky (right dates to use)
* Looking-up the right phase type for the alignment is tricky (use [next vs prev phase](https://github.com/killbill/killbill/blob/76d1b721793a031de7d32f77b18c2bfa8690c3b9/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BillCycleDayCalculator.java#L78))
* It's unclear if some edge-case scenarii are tested ([transition across pricelists](https://github.com/killbill/killbill/blob/76d1b721793a031de7d32f77b18c2bfa8690c3b9/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BillCycleDayCalculator.java#L85), [null phase](https://github.com/killbill/killbill/blob/76d1b721793a031de7d32f77b18c2bfa8690c3b9/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/BillCycleDayCalculator.java#L137), ...)

Maybe it's just a matter of re-visiting the Catalog APIs?

**Comment by sbrossie** [comment]
I think there is also work in the subscription base internal api for your bullet 2:
> Looking-up the right phase type for the alignment is tricky (use next vs prev phase)

**Comment by sbrossie** [comment]
Providing some update on this ticket based on recent interaction on the [mailing list](https://groups.google.com/forum/#!searchin/killbilling-users/azim%7Csort:relevance/killbilling-users/i9HESgr_RSI/mPxXBSViAwAJ).

On the catalog side, our apis are indeed a bit complicated to use, because we have several forms for different purpose:
* `findPlan(String name, DateTime requestedDate)`: This form is used to find the version of a `Plan` entry in a given catalog version (last catalog version whose `effectiveDate` is before or equals to the provided `requestedDate`. For instance, when creating a new `Subscription`, subscription code will invoke that method with a `requestedDate=clock.getUTCNow()` to find the `Plan` version (if it still exists from latest version).
* `findPlan(String name, DateTime requestedDate, DateTime subscriptionStartDate)`: This form is used to find the correct `Plan` version: The `requestedDate` is used to select the set of possible catalog versions (whose `effectiveDate` are before or equals to the provided `requestedDate`). Code looks at all possible version backward and attempts to select correct version of `Plan` based on following criteria:
  * If `subscriptionStartDate` is after current catalog version `effectiveDate` (new subscription), then use it.
  * If not,  will look for a `effectiveDateForExistingSubscriptions` to see if new price applies for older subscription

This complicated apis put some burden on the clients (which need to be well aware of which api to use, and also be in a position to have the right info to invoke the api correctly  (e.g `subscriptionStartDate` is not necessarily available at the time client tries to use catalog)

**Comment by sbrossie** [comment]
> Looking-up the right phase type for the alignment is tricky (use next vs prev phase)

Another topic, is the topic of the subscription (base) apis that are used by junction: Those provide the `EffectiveSubscriptionInternalEvent` which offer the `prev` `next` methods which need to be interpreted correctly depending on the type of transition (e.g in a `CANCEL` use case, the `next` will be null and current info will need to be interpreted by looking at the `prev`)

**Comment by sbrossie** [comment]
After discussing with @pierre, we would like to at least fix the code in junction, from the [previous comment](https://github.com/killbill/killbill/issues/56#issuecomment-291656140):

* Remove all the logic in `DefaultBillingEvent` that needs to understand the state of transitions -- example [here](https://github.com/killbill/killbill/blob/killbill-0.18.7/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultBillingEvent.java#L71)
* Same in `DefaultInternalBillingApi` [here](https://github.com/killbill/killbill/blob/killbill-0.18.7/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultInternalBillingApi.java#L234)

**Comment by MusharrafSakran** [comment]
Hi everyone,

We are facing this issue in v0.18.11 when killbill is trying to generate the invoices, here we go:





2017-08-03T11:06:14,023+0000 lvl='INFO', log='TenantCatalogCacheLoader', th='http-nio-8080-exec-1', xff='', rId='c4b5b520-d5a2-47cd-99bd-bc57c7b6616a', aRId='', tRId='2', Loading catalog cache for tenantRecordId='2'
2017-08-03T11:06:14,721+0000 lvl='INFO', log='XMLLoader', th='http-nio-8080-exec-1', xff='', rId='c4b5b520-d5a2-47cd-99bd-bc57c7b6616a', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-08-03T11:06:15,207+0000 lvl='INFO', log='XMLLoader', th='http-nio-8080-exec-1', xff='', rId='c4b5b520-d5a2-47cd-99bd-bc57c7b6616a', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-08-03T11:06:15,215+0000 lvl='INFO', log='XMLLoader', th='http-nio-8080-exec-1', xff='', rId='c4b5b520-d5a2-47cd-99bd-bc57c7b6616a', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-08-03T11:06:15,439+0000 lvl='WARN', log='LoggingResponse', th='http-nio-8080-exec-1', xff='', rId='c4b5b520-d5a2-47cd-99bd-bc57c7b6616a', aRId='77', tRId='2', Bad request
org.killbill.billing.subscription.api.user.SubscriptionBaseApiException: Could not find a plan matching spec: (plan: 'virtual-data-center-52_plan', product: 'undefined', billing period: 'undefined', pricelist 'undefined')
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getSubscriptionsForAccount(DefaultSubscriptionInternalApi.java:533)
	at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForAccount(EventsStreamBuilder.java:126)
	at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementApiBase.getAllEntitlementsForAccount(DefaultEntitlementApiBase.java:117)
	at org.killbill.billing.entitlement.api.DefaultSubscriptionApi.getSubscriptionBundlesForAccount(DefaultSubscriptionApi.java:454)
	at org.killbill.billing.entitlement.api.DefaultSubscriptionApi.getSubscriptionBundle(DefaultSubscriptionApi.java:157)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
	at org.killbill.billing.entitlement.api.DefaultSubscriptionApi.getActiveSubscriptionBundleForExternalKey(DefaultSubscriptionApi.java:191)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
	at org.killbill.billing.jaxrs.resources.BundleResource.getBundleByKey(BundleResource.java:149)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:110)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.killbill.billing.catalog.api.CatalogApiException: Could not find a plan matching spec: (plan: 'virtual-data-center-52_plan', product: 'undefined', billing period: 'undefined', pricelist 'undefined')
	at org.killbill.billing.catalog.VersionedCatalog.findCatalogPlanEntry(VersionedCatalog.java:202)
	at org.killbill.billing.catalog.VersionedCatalog.findPlan(VersionedCatalog.java:317)
	at org.killbill.billing.subscription.api.user.DefaultSubscriptionBase.rebuildTransitions(DefaultSubscriptionBase.java:750)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.createSubscriptionForInternalUse(DefaultSubscriptionDao.java:1033)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.buildBundleSubscriptions(DefaultSubscriptionDao.java:863)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getSubscriptionsForAccount(DefaultSubscriptionDao.java:363)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getSubscriptionsForAccount(DefaultSubscriptionInternalApi.java:526)
	... 80 common frames omitted









is this gonna be solved nearly by any chance?

**Comment by sbrossie** [comment]
@MusharrafSakran I don't think this this issue has anything to do with #56; Instead this seems related to #760 -- which we thought was fixed, but maybe not. Please use the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) to report any issues.

**Comment by pierre** [comment]
The catalog APIs have been updated in 0.20.
