### ISSUE TITLE
Changing plan using Price override to the same plan fails

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#596]
The issue was reported on the [mailing list](https://groups.google.com/forum/#!topic/killbilling-users/zPZx1ht4nzk), and i was able to reproduce the issue with the following code snippet:

```
     #### Insert into integration test TestPriceOverride:
    def test_change_ao_plan_with_override


      bp = create_entitlement_base(@account.account_id, 'Sports', 'MONTHLY', 'DEFAULT', @user, @options)
      check_entitlement(bp, 'Sports', 'BASE', 'MONTHLY', 'DEFAULT', DEFAULT_KB_INIT_DATE, nil)
      wait_for_expected_clause(1, @account, @options, &@proc_account_invoices_nb)

      kb_clock_add_days(30, nil, @options)
      check_next_invoice_amount(2, 500.0, '2013-08-31', @account, @options, &@proc_account_invoices_nb)

      ao = create_entitlement_ao(@account.account_id, bp.bundle_id, 'OilSlick', 'MONTHLY', 'DEFAULT', @user, @options)
      check_entitlement(ao, 'OilSlick', 'ADD_ON', 'MONTHLY', 'DEFAULT', "2013-08-31", nil)
      wait_for_expected_clause(3, @account, @options, &@proc_account_invoices_nb)


      kb_clock_add_days(2, nil, @options)

      overrides1 = []
      override1 = KillBillClient::Model::PhasePriceOverrideAttributes.new
      override1.phase_type = 'EVERGREEN'
      override1.recurring_price = 100.0
      overrides1 << override1


      ao = ao.change_plan({:productName => 'OilSlick', :billingPeriod => 'MONTHLY', :priceList => 'DEFAULT', :priceOverrides => overrides1}, @user, nil, nil, nil, nil, false, @options)
      wait_for_expected_clause(4, @account, @options, &@proc_account_invoices_nb)

    end
```

As reported killbill throws following error:

```
2016-08-08T15:47:47,053+0000 lvl='WARN', log='LoggingResponse', th='qtp280291320-34', xff='', rId='392f28d2-15da-42ff-b085-5b86b0b75d30', aRId='2424', tRId='507', Bad request
org.killbill.billing.subscription.api.user.SubscriptionBaseApiException: Attempting to change plan from (product: 'OilSlick', billing period: 'MONTHLY', pricelist 'DEFAULT') to (product: 'OilSlick', billing period: 'MONTHLY', pricelist 'DEFAULT'). This transition is not allowed by catalog rules
	at org.killbill.billing.subscription.api.user.DefaultSubscriptionBaseApiService.getPlanChangeResult(DefaultSubscriptionBaseApiService.java:439)
	at org.killbill.billing.subscription.api.user.DefaultSubscriptionBaseApiService.dryRunChangePlan(DefaultSubscriptionBaseApiService.java:353)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getDryRunChangePlanEffectiveDate(DefaultSubscriptionInternalApi.java:434)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$3.doCall(DefaultEntitlement.java:506)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$3.doCall(DefaultEntitlement.java:495)

```

**Comment by sbrossie** [comment]
This is a restriction in the catalog that prevents from changing to the same plan/pricelist, but because use specifies a price override, this should probably be allowed.

**Comment by sbrossie** [comment]
I just investigated the issue a bit further, and the problem comes from the [catalog code that is called to compute the default `BillingActionPolicy`](https://github.com/killbill/killbill/blob/killbill-0.16.7/catalog/src/main/java/org/killbill/billing/catalog/rules/DefaultPlanRules.java#L152): The code does not have rules to compute `BillingActionPolicy` when making a change from and to the same `Plan`.

**Comment by sbrossie** [comment]
However there is an **easy workaround** by specifying the `BillingActionPolicy` during the change call:
* Using the [java client](https://github.com/killbill/killbill-client-java/blob/killbill-client-java-0.23.2/src/main/java/org/killbill/billing/client/KillBillClient.java#L670), specify one of the [supported value](https://github.com/killbill/killbill-api/blob/killbill-api-0.33.1/src/main/java/org/killbill/billing/catalog/api/BillingActionPolicy.java#L23)
* Using JAXRS API: Specify query param 'billingPolicy' with one of the [supported value](https://github.com/killbill/killbill-api/blob/killbill-api-0.33.1/src/main/java/org/killbill/billing/catalog/api/BillingActionPolicy.java#L23)
* Using the java API :
```
changePlanWithPolicy("Telescopic-Scope", BillingPeriod.MONTHLY, PriceListSet.DEFAULT_PRICELIST_NAME, overrides, new LocalDate(2012, 5, 5), BillingActionPolicy.IMMEDIATE, ImmutableList.<PluginProperty>of(), callContext);
```
