### ISSUE TITLE
Getting 'We're sorry, but something went wrong'

### ISSUE THREAD

**Issue by axcesstech** [killbill/killbill#633]
I just installed killbill. When I login I get 'We're sorry, but something went wrong'.

When I start the server I see the following messages on the console:

Caused by: org.h2.jdbc.JdbcSQLException: Table "NOTIFICATIONS" not found; SQL statement:
    select
                 record_id
                  ,       class_name
                  , event_json
                  , user_token
                  , created_date
                  , creating_owner
                  , processing_owner
                  , processing_available_date
                  , processing_state
                  , error_count
                  , search_key1
                  , search_key2
                  , future_user_token
                  , effective_date
                  , queue_name
    from notifications
    where
          effective_date <= ?
          and processing_state != 'PROCESSED'
          and processing_state != 'REMOVED'
      and creating_owner = 'creatorName-unknown'
          and (processing_owner IS NULL OR processing_available_date <= ?)
    order by
              effective_date asc
            , created_date asc
            , record_id
    limit ?
    ; [42102-186]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5251)
	at org.h2.command.Parser.readTableFilter(Parser.java:1235)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1874)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1983)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1868)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1689)
	at org.h2.command.Parser.parseSelect(Parser.java:1677)
	at org.h2.command.Parser.parsePrepared(Parser.java:433)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:446)
	at org.h2.engine.Session.prepareCommand(Session.java:388)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:277)
	at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:268)
	at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.prepareStatement(ConnectionJavassistProxy.java)
	at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:48)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1304)

**Comment by pierre** [comment]
> Caused by: org.h2.jdbc.JdbcSQLException: Table "NOTIFICATIONS" not found

It looks like the DDL wasn't fully installed and some tables are missing.

A few thoughts:

* Did you follow http://docs.killbill.io/0.16/getting_started.html? If so, was there any error during the installation?
* Try deleting the h2 database under /var/tmp/killbill and re-install
* Re-install the DDL (see http://docs.killbill.io/0.16/getting_started.html#_database). Switching to MySQL would be more convenient

**Comment by axcesstech** [comment]
Hi Pierre,
Thanks for your quick response. As per your advice, I created a mysql dm, deployed ddl.sql and change teh catalina conf file with the DB reference. Now I am get the following error:

2016-10-22T12:01:27,722+0000 lvl='ERROR', log='Cache', th='localhost-startStop-1', xff='', rId='', aRId='', tRId='', Unable to set localhost. This prevents creation of a GUID. Cause was: ip-10-0-0-111: ip-10-0-0-111: unknown error
java.net.UnknownHostException: ip-10-0-0-111: ip-10-0-0-111: unknown error
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
        at net.sf.ehcache.Cache.<clinit>(Cache.java:222)
        at net.sf.ehcache.config.ConfigurationHelper.createCache(ConfigurationHelper.java:305)
        at net.sf.ehcache.config.ConfigurationHelper.createDefaultCache(ConfigurationHelper.java:223)
        at net.sf.ehcache.CacheManager.configure(CacheManager.java:796)
        at net.sf.ehcache.CacheManager.doInit(CacheManager.java:471)
        at net.sf.ehcache.CacheManager.init(CacheManager.java:395)
        at net.sf.ehcache.CacheManager.<init>(CacheManager.java:270)
        at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1116)
        at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1060)
        at net.sf.ehcache.CacheManager.create(CacheManager.java:1035)
        at org.killbill.billing.util.cache.EhCacheCacheManagerProvider.get(EhCacheCacheManagerProvider.java:91)
        at org.killbill.billing.util.cache.EhCacheCacheManagerProvider.get(EhCacheCacheManagerProvider.java:43)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:53)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)

Thanks again for looking into this.

**Comment by pierre** [comment]
> 2016-10-22T12:01:27,722+0000 lvl='ERROR', log='Cache', th='localhost-startStop-1', xff='', rId='', aRId='', tRId='', Unable to set localhost. This prevents creation of a GUID. Cause was: ip-10-0-0-111: ip-10-0-0-111: unknown error

It looks like your host is mis-configured (`ip-10-0-0-111` isn't a valid IP address).

Since it doesn't look like there is a bug here, I'm going to close this. Feel free to use the mailing-list (https://groups.google.com/forum/#!forum/killbilling-users) for support and installation questions.

**Comment by axcesstech** [comment]
Thanks for the pointer. I managed to find the issue. AWS was setting the hostname as IP-<private ip address>.
