### ISSUE TITLE
Creating an ADD_ON on a pending subscription fails

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#681]
The code is trying to retrieve the active `BASE` subscription (but there are none so it fails with following trace.

Probably we should have that fail is the `start_date` of the ADD_ON subscription is prior the `start_date` of the BP, but otherwise i expect it should work.

```
2016-12-30T21:47:25,050+0000 lvl='WARN', log='LoggingResponse', th='qtp1442707449-28', xff='', rId='b7b5e6a1-29a1-44bd-a4a5-7cf31e56a083', aRId='7194', tRId='5357', Bad request
org.killbill.billing.entitlement.api.EntitlementApiException: Could not find base subscription for bundle e6142044-63fa-486a-bf62-3042d18f3480
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi$3.doCall(DefaultEntitlementApi.java:297)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi$3.doCall(DefaultEntitlementApi.java:290)
	at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:97)
	at org.killbill.billing.entitlement.api.DefaultEntitlementApi.addEntitlement(DefaultEntitlementApi.java:326)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doOperation(SubscriptionResource.java:218)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$1.doOperation(SubscriptionResource.java:203)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource$EntitlementCallCompletion.withSynchronization(SubscriptionResource.java:808)
	at org.killbill.billing.jaxrs.resources.SubscriptionResource.createEntitlement(SubscriptionResource.java:248)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:67)
...
```

**Comment by sbrossie** [comment]
I lost the context of how that happened, so i am not sure what to do next.
