### ISSUE TITLE
Loading same catalog multiple times should fail during load operation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#690]
Currently loading a second identical catalog succeeds but then later when the catalog subsystem tries to validate the `VersionnedCatalog`, things break down (also we don't print the validation error which makes it hard to understand why:

```
2017-01-09T22:17:35,851+0000 lvl='WARN', log='LoggingResponse', th='qtp1442707449-35', xff='', rId='0c1f20f2-0717-48d3-881e-cbfa4419cd8a', aRId='', tRId='5896', Internal error
net.sf.ehcache.CacheException: Exception on load for key 5896
	at net.sf.ehcache.Cache.getWithLoader(Cache.java:1867)
	at net.sf.ehcache.constructs.EhcacheDecoratorAdapter.getWithLoader(EhcacheDecoratorAdapter.java:267)
	at org.killbill.billing.util.cache.EhCacheBasedCacheController.getWithOrWithoutCacheLoaderArgument(EhCacheBasedCacheController.java:79)
	at org.killbill.billing.util.cache.EhCacheBasedCacheController.get(EhCacheBasedCacheController.java:45)
	at org.killbill.billing.catalog.caching.EhCacheCatalogCache.getCatalog(EhCacheCatalogCache.java:106)
	at org.killbill.billing.catalog.DefaultCatalogService.getCatalog(DefaultCatalogService.java:104)
	at org.killbill.billing.catalog.DefaultCatalogService.getFullCatalog(DefaultCatalogService.java:95)
	at org.killbill.billing.catalog.api.user.DefaultCatalogUserApi.getCatalog(DefaultCatalogUserApi.java:81)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:4

...

Caused by: java.lang.IllegalStateException: Failed to de-serialize catalog for tenantRecordId='5896'
	at org.killbill.billing.util.cache.TenantCatalogCacheLoader.load(TenantCatalogCacheLoader.java:78)
	at net.sf.ehcache.Cache.loadWithRegisteredLoaders(Cache.java:3394)
	at net.sf.ehcache.Cache.loadValueUsingLoader(Cache.java:3376)
	at net.sf.ehcache.Cache.getWithLoader(Cache.java:1859)
	... 81 common frames omitted
Caused by: org.killbill.billing.catalog.api.CatalogApiException: Invalid catalog for tenant : 5896
	at org.killbill.billing.catalog.io.VersionedCatalogLoader.load(VersionedCatalogLoader.java:135)
	at org.killbill.billing.catalog.caching.EhCacheCatalogCache$1.loadCatalog(EhCacheCatalogCache.java:154)
	at org.killbill.billing.util.cache.TenantCatalogCacheLoader.load(TenantCatalogCacheLoader.java:76)
	... 84 common frames omitted
Caused by: org.killbill.xmlloader.ValidationException: null
	at org.killbill.xmlloader.XMLLoader.initializeAndValidate(XMLLoader.java:108)
	at org.killbill.billing.catalog.io.VersionedCatalogLoader.load(VersionedCatalogLoader.java:131)
	... 86 common frames omitted

```

**Comment by sbrossie** [comment]
When debugging through the code, we see that the Validation code actually works well:

```
0 = {org.killbill.xmlloader.ValidationError@19481} "Catalog effective date 'Tue Jul 08 00:00:00 GMT 2014' already exists for a previous version [null] (class org.killbill.billing.catalog.VersionedCatalog:)\n"
1 = {org.killbill.xmlloader.ValidationError@19481} "Catalog effective date 'Tue Jul 08 00:00:00 GMT 2014' already exists for a previous version [null] (class org.killbill.billing.catalog.VersionedCatalog:)\n"
```

However it is not invoked at the time we load the catalog and so the error happens only at the time catalog code tries to deserialize catalog which is too late.
