### ISSUE TITLE
bugs with deserializing and symbols in catalog name

### ISSUE THREAD

**Issue by bkhasanov** [killbill/killbill#699]
For adding `+` symbol in catalouge name to throw `500`error is annoying 👎 

Here is the log 

```2017-01-27T06:29:08,648+0000 lvl='INFO', log='TenantCatalogCacheLoader', th='http-bio-8080-exec-2', xff='', rId='48acffc5-bb0b-4207-975a-45dba2c1c685', aRId='', tRId='4', Loading catalog cache for tenantRecordId='4'
2017-01-27T06:29:08,689+0000 lvl='WARN', log='VersionedCatalogLoader', th='http-bio-8080-exec-2', xff='', rId='48acffc5-bb0b-4207-975a-45dba2c1c685', aRId='', tRId='4', Failed to load catalog for tenantRecordId='4'
javax.xml.bind.UnmarshalException: null
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	... 99 common frames omitted	

Caused by: org.xml.sax.SAXParseException: cvc-datatype-valid.1.2.1: 'Lamuz+' is not a valid value for 'NCName'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	
	... 102 common frames omitted
2017-01-27T06:29:08,691+0000 lvl='WARN', log='LoggingResponse', th='http-bio-8080-exec-2', xff='', rId='48acffc5-bb0b-4207-975a-45dba2c1c685', aRId='', tRId='4', Internal error
net.sf.ehcache.CacheException: Exception on load for key 4```




########## Another BUG with  deserializing ################


2017-01-27T06:57:51,440+0000 lvl='INFO', log='TenantCatalogCacheLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Loading catalog cache for tenantRecordId='2'
2017-01-27T06:57:51,477+0000 lvl='INFO', log='XMLLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-01-27T06:57:51,524+0000 lvl='INFO', log='XMLLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-01-27T06:57:51,579+0000 lvl='INFO', log='XMLLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-01-27T06:57:51,649+0000 lvl='INFO', log='XMLLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Errors: 0 for /tenantCatalog
2017-01-27T06:57:51,649+0000 lvl='INFO', log='XMLLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Errors: 2 for /tenantCatalog
2017-01-27T06:57:51,649+0000 lvl='WARN', log='VersionedCatalogLoader', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Failed to load catalog for tenantRecordId='2'
org.killbill.xmlloader.ValidationException: null
	at org.killbill.xmlloader.XMLLoader.initializeAndValidate(XMLLoader.java:108)
	at org.killbill.billing.catalog.io.VersionedCatalogLoader.load(VersionedCatalogLoader.java:131)
	at org.killbill.billing.catalog.caching.EhCacheCatalogCache$1.loadCatalog(EhCacheCatalogCache.java:154)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-01-27T06:57:51,655+0000 lvl='WARN', log='LoggingResponse', th='http-bio-8080-exec-9', xff='', rId='b226ee8b-4cc6-42a1-99b2-1e7766275dc3', aRId='', tRId='2', Internal error
net.sf.ehcache.CacheException: Exception on load for key 2
	at net.sf.ehcache.Cache.getWithLoader(Cache.java:1867)
	at net.sf.ehcache.constructs.EhcacheDecoratorAdapter.getWithLoader(EhcacheDecoratorAdapter.java:267)
	at org.killbill.billing.util.cache.EhCacheBasedCacheController.getWithOrWithoutCacheLoaderArgument(EhCacheBasedCacheController.java:79)

Caused by: java.lang.IllegalStateException: Failed to de-serialize catalog for tenantRecordId='2'
	at org.killbill.billing.util.cache.TenantCatalogCacheLoader.load(TenantCatalogCacheLoader.java:78)
	at net.sf.ehcache.Cache.loadWithRegisteredLoaders(Cache.java:3394)
	at net.sf.ehcache.Cache.loadValueUsingLoader(Cache.java:3376)
	at net.sf.ehcache.Cache.getWithLoader(Cache.java:1859)
	... 78 common frames omitted

Caused by: org.killbill.billing.catalog.api.CatalogApiException: Invalid catalog for tenant : 2
	at org.killbill.billing.catalog.io.VersionedCatalogLoader.load(VersionedCatalogLoader.java:135)
	at org.killbill.billing.catalog.caching.EhCacheCatalogCache$1.loadCatalog(EhCacheCatalogCache.java:154)
	at org.killbill.billing.util.cache.TenantCatalogCacheLoader.load(TenantCatalogCacheLoader.java:76)
	... 81 common frames omitted

Caused by: org.killbill.xmlloader.ValidationException: null
	at org.killbill.xmlloader.XMLLoader.initializeAndValidate(XMLLoader.java:108)
	at org.killbill.billing.catalog.io.VersionedCatalogLoader.load(VersionedCatalogLoader.java:131)
	... 83 common frames omitted

**Comment by bkhasanov** [comment]
Not sure whether my report relates to this  one #690

**Comment by bkhasanov** [comment]
Plus it doesn't understand Russian (((( 

`Caused by: org.xml.sax.SAXParseException: cvc-datatype-valid.1.2.1: '????????????????????' is not a valid value for 'NCName'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)`

**Comment by petrkoshkin** [comment]
Dear colleague, please be more polite when you asking for help and you will see how the world makes the same. 
Regarding this error  'Lamuz+' is not a valid value for 'NCName'.
As you didn't attached your catalog xml I can suggest that you have invalid xml. This error is typical in xml world when you try to use special chars as the name of XML element

Thank you

**Comment by bkhasanov** [comment]
@petrkoshkin didn't mean to be rude )) it just my reacted out of frustration that such a simple bug would make editing of catalog impossible and throw 500, it is my perfectionism to blame :)
