### ISSUE TITLE
Update Account BCD failure under high load

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#711]
```
2017-02-24T19:39:31,933+0000 lvl='WARN', log='InvoiceDispatcher', th='notifications-th', xff='', rId='', aRId='30005', tRId='2125', Failed to retrieve BillingEvents for accountId='c970843a-49cb-4205-8d56-e186951084a0', dryRunArguments='null'
org.killbill.billing.account.api.AccountApiException: Account update failed.
	at org.killbill.billing.account.api.svcs.DefaultAccountInternalApi.updateBCD(DefaultAccountInternalApi.java:95)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.addBillingEventsForSubscription(DefaultInternalBillingApi.java:222)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.addBillingEventsForBundles(DefaultInternalBillingApi.java:168)
	at org.killbill.billing.junction.plumbing.billing.DefaultInternalBillingApi.getBillingEventsForAccountAndUpdateAccountBCD(DefaultInternalBillingApi.java:109)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:284)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:256)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountFromNotificationOrBusEvent(InvoiceDispatcher.java:233)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:215)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:190)
	at org.killbill.billing.invoice.InvoiceListener.handleNextBillingDateEvent(InvoiceListener.java:108)
	at org.killbill.billing.invoice.notification.DefaultNextBillingDateNotifier.processEventForInvoiceGeneration(DefaultNextBillingDateNotifier.java:116)
	at org.killbill.billing.invoice.notification.DefaultNextBillingDateNotifier.access$400(DefaultNextBillingDateNotifier.java:40)
	at org.killbill.billing.invoice.notification.DefaultNextBillingDateNotifier$1.handleReadyNotification(DefaultNextBillingDateNotifier.java:89)
	at org.killbill.notificationq.NotificationQueueDispatcher.handleNotificationWithMetrics(NotificationQueueDispatcher.java:203)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:51)
	at org.killbill.notificationq.dispatching.NotificationCallableCallback.dispatch(NotificationCallableCallback.java:32)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Issue is that `currentAccountBCD` is computed as 0 [here](https://github.com/killbill/killbill/blob/e5ed0dc60eee877470192a69c9d2d6923b4e207d/junction/src/main/java/org/killbill/billing/junction/plumbing/billing/DefaultInternalBillingApi.java#L220) even though it is set on the account at the time of the account creation (calling `accountApi.getBCD(account.getId(), context)` in the debugger confirms the non-null account BCD value).

Might be a cache loader issue?

**Comment by pierre** [comment]
Could be related: https://jira.terracotta.org/jira/browse/EHC-1132.
