### ISSUE TITLE
Kpm Installation failure (error in chozo gem)

### ISSUE THREAD

**Issue by muichkine** [killbill/killbill#714]
```
olivier@debian:~/src$ kpm install
undefined method 'split' for :mid:Symbol
/home/olivier/.rvm/gems/ruby-2.4.0/gems/chozo-0.6.1/lib/chozo/core_ext/hash/dotted_paths.rb:82:in 'dig'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable/impl.rb:10:in 'dig'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable/impl.rb:10:in '_valid_method?'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:201:in '_delegator_method'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:180:in 'def_instance_delegator'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156:in 'block in def_instance_delegators'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:155:in 'each'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:155:in 'def_instance_delegators'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/nexus_cli-4.1.1/lib/nexus_cli/base_remote.rb:7:in '<class:BaseRemote>'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/nexus_cli-4.1.1/lib/nexus_cli/base_remote.rb:2:in '<module:NexusCli>'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/nexus_cli-4.1.1/lib/nexus_cli/base_remote.rb:1:in '<top (required)>'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/nexus_cli-4.1.1/lib/nexus_cli/remote/pro_remote.rb:2:in '<module:NexusCli>'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/nexus_cli-4.1.1/lib/nexus_cli/remote/pro_remote.rb:1:in '<top (required)>'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
/home/olivier/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/nexus_cli-4.1.1/lib/nexus_cli/remote_factory.rb:20:in 'create'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/kpm-0.4.0/lib/kpm/base_artifact.rb:48:in 'nexus_remote'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/kpm-0.4.0/lib/kpm/killbill_server_artifact.rb:10:in 'versions'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/kpm-0.4.0/lib/kpm/installer.rb:19:in 'build_default_config'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/kpm-0.4.0/lib/kpm/installer.rb:11:in 'from_file'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/kpm-0.4.0/lib/kpm/tasks.rb:40:in 'install'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in 'run'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in 'invoke_command'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in 'dispatch'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in 'start'
/home/olivier/.rvm/gems/ruby-2.4.0/gems/kpm-0.4.0/bin/kpm:6:in '<top (required)>'
/home/olivier/.rvm/gems/ruby-2.4.0/bin/kpm:22:in 'load'
/home/olivier/.rvm/gems/ruby-2.4.0/bin/kpm:22:in '<main>'
/home/olivier/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in 'eval'
/home/olivier/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in '<main>'
```

ruby 2.4.0

**Comment by pierre** [comment]
Do you have a custom `kpm.yml`?

**Comment by muichkine** [comment]
No, straight of the box following your installation tutorial.

**Comment by muichkine** [comment]
This does not happen with ruby 2.1 on the same computer. Haven't tried 2.2/3 yet

**Comment by pierre** [comment]
It looks like `dig` was introduced with [Ruby 2.3.0](https://github.com/ruby/ruby/blob/v2_3_0_preview1/ChangeLog#L141-L148). The signature isn't compatible with the version from [chozo](https://github.com/reset/chozo/blob/ba88aff29bef4b2f56090a8ad1a4ba5a165786e8/lib/chozo/core_ext/hash/dotted_paths.rb#L79) unfortunately.

`chozo` is a transitive dependency from `nexus_cli` that we're [looking to deprecate](https://groups.google.com/forum/#!topic/killbilling-users/7LHcqDq0JiU). We might have to do it sooner than expected.

A workaround for now is to use Ruby 2.2 or below.

**Comment by pierre** [comment]
Tracked by https://github.com/killbill/killbill-cloud/issues/74.
