### ISSUE TITLE
This price does not have a value for the currency 'null'

### ISSUE THREAD

**Issue by niiamon-rag** [killbill/killbill#819]
Hi,

I'm having a pretty odd issue here. I have a catalog:

```xml
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CatalogSchema.xsd ">

    <effectiveDate>2017-02-08T00:00:00+00:01</effectiveDate>
    <catalogName>CatalogForTesting</catalogName>
    <recurringBillingMode>IN_ADVANCE</recurringBillingMode>

    <currencies>
        <currency>USD</currency>
    </currencies>

    <products>
        <product name="Premium">
            <category>BASE</category>
        </product>
    </products>

    <rules>
        <changePolicy>
            <changePolicyCase>
                <policy>IMMEDIATE</policy>
            </changePolicyCase>
        </changePolicy>
        <changeAlignment>
            <changeAlignmentCase>
                <alignment>START_OF_BUNDLE</alignment>
            </changeAlignmentCase>
        </changeAlignment>
        <cancelPolicy>
            <cancelPolicyCase>
                <policy>IMMEDIATE</policy>
            </cancelPolicyCase>
        </cancelPolicy>
        <createAlignment>
            <createAlignmentCase>
                <alignment>START_OF_BUNDLE</alignment>
            </createAlignmentCase>
        </createAlignment>
        <billingAlignment>
            <billingAlignmentCase>
                <alignment>ACCOUNT</alignment>
            </billingAlignmentCase>
        </billingAlignment>
        <priceList>
            <priceListCase>
                <toPriceList>DEFAULT</toPriceList>
            </priceListCase>
        </priceList>
    </rules>

    <plans>
        <plan name="premium-monthly">
            <product>Premium</product>
            <finalPhase type="EVERGREEN">
                <duration>
                    <unit>UNLIMITED</unit>
                </duration>
                <recurring>
                    <billingPeriod>MONTHLY</billingPeriod>
                    <recurringPrice>
                        <price>
                            <currency>USD</currency>
                            <value>500.00</value>
                        </price>
                    </recurringPrice>
                </recurring>
            </finalPhase>
        </plan>
        <plan name="premium-weekly">
            <product>Premium</product>
            <finalPhase type="EVERGREEN">
                <duration>
                    <unit>UNLIMITED</unit>
                </duration>
                <recurring>
                    <billingPeriod>WEEKLY</billingPeriod>
                    <recurringPrice>
                        <price>
                            <currency>USD</currency>
                            <value>150.00</value>
                        </price>
                    </recurringPrice>
                </recurring>
            </finalPhase>
        </plan>
        <plan name="premium-daily">
            <product>Premium</product>
            <finalPhase type="EVERGREEN">
                <duration>
                    <unit>UNLIMITED</unit>
                </duration>
                <recurring>
                    <billingPeriod>DAILY</billingPeriod>
                    <recurringPrice>
                        <price>
                            <currency>USD</currency>
                            <value>25.00</value>
                        </price>
                    </recurringPrice>
                </recurring>
            </finalPhase>
        </plan>
    </plans>

    <priceLists>
        <defaultPriceList name="DEFAULT">
            <plans>
                <plan>premium-monthly</plan>
                <plan>premium-weekly</plan>
                <plan>premium-daily</plan>
            </plans>
        </defaultPriceList>
    </priceLists>
</catalog>
```

I am able to create an account, associate a payment method with it and then create a subscription. However, I at the end of creating a subscription, I see this issue:

```log
9189 < Location: http://localhost:8080/1.0/kb/subscriptions/fa4fc6ba-3776-4d64-967f-0bf4bafcafa9
9189 < Content-Type: application/json
9189 < Vary: Accept-Encoding
9189 <

2017-11-10T12:51:45,341+0000 lvl='INFO', log='DefaultInternalBillingApi', th='bus_events-th', xff='', rId='', aRId='11', tRId='1', Computed billing events for accountId='25b66324-c7f3-466e-a3a1-0819815ab9a9'
DefaultBillingEvent{type=CREATE, effectiveDate=2017-11-10T12:51:45.000Z, planPhaseName=premium-daily-evergreen, subscriptionId=fa4fc6ba-3776-4d64-967f-0bf4bafcafa9, totalOrdering=3}
2017-11-10T12:51:45,366+0000 lvl='WARN', log='InvoiceListener', th='bus_events-th', xff='', rId='', aRId='11', tRId='1', Unable to process event DefaultEffectiveSubscriptionEvent{bundleId=8df0b404-4b2f-4aaa-85b6-9d93dcc7044b, totalOrdering=0, subscriptionId=fa4fc6ba-3776-4d64-967f-0bf4bafcafa9, eventId=7f711f05-56be-4873-84b6-c6d6e9ffdff6, requestedTransitionTime=2017-11-10T12:51:45.000Z, effectiveTransitionTime=2017-11-10T12:51:45.000Z, previousState=null, previousPriceList='null', previousBillCycleDayLocal='null', previousPlan='null', previousPhase='null', nextState=ACTIVE, nextPriceList='DEFAULT', nextBillCycleDayLocal='null', nextPlan='premium-daily', nextPhase='premium-daily-evergreen', remainingEventsForUserOperation=0, transitionType=CREATE, startDate=2017-11-10T12:51:45.000Z}
org.killbill.billing.invoice.api.InvoiceApiException: This price does not have a value for the currency 'null'.
	at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.processRecurringEvent(FixedAndRecurringInvoiceItemGenerator.java:259)
	at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.processRecurringBillingEvents(FixedAndRecurringInvoiceItemGenerator.java:148)
	at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.generateItems(FixedAndRecurringInvoiceItemGenerator.java:108)
	at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:84)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:385)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:288)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:251)
	at org.killbill.billing.invoice.InvoiceDispatcher.processAccountFromNotificationOrBusEvent(InvoiceDispatcher.java:228)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:210)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:185)
	at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:181)
	at org.killbill.billing.invoice.InvoiceListener.handleSubscriptionTransition(InvoiceListener.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$ImmediateDispatcher.dispatch(Dispatcher.java:200)
	at com.google.common.eventbus.EventBusThatThrowsException.postWithException(EventBusThatThrowsException.java:65)
	at org.killbill.bus.DefaultPersistentBus.dispatchBusEventWithMetrics(DefaultPersistentBus.java:314)
	at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:40)
	at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:29)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
	at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.killbill.billing.catalog.api.CatalogApiException: This price does not have a value for the currency 'null'.
	at org.killbill.billing.catalog.DefaultInternationalPrice.getPrice(DefaultInternationalPrice.java:87)
	at org.killbill.billing.junction.plumbing.billing.DefaultBillingEvent.getRecurringPrice(DefaultBillingEvent.java:316)
	at org.killbill.billing.junction.plumbing.billing.DefaultBillingEvent.getRecurringPrice(DefaultBillingEvent.java:209)
	at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.processRecurringEvent(FixedAndRecurringInvoiceItemGenerator.java:234)
	... 32 common frames omitted
```

This is strange since I have the currency defined on the plans within the catalog and in Kaui, my plans list the correct currency.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.
