### ISSUE TITLE
Invoice not triggered for Subscription Upgrade while refunds applied in previous subscription

### ISSUE THREAD

**Issue by Arulraj12** [killbill/killbill#848]
Hi,
**My catalog is below,**

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<catalog>
  <effectiveDate>2016-05-10T00:00:30Z</effectiveDate>
  <catalogName>DEFAULT</catalogName>
  <recurringBillingMode>IN_ADVANCE</recurringBillingMode>
  <currencies>
    <currency>USD</currency>
  </currencies>
  <units/>
  <products>
    <product name="product1">
      <category>BASE</category>
      <included />
      <available />
      <limits />
    </product>
	<product name="product2">
      <category>BASE</category>
      <included />
      <available />
      <limits />
    </product>
  </products>
  <rules>
    <changePolicy>
      <changePolicyCase>
        <policy>IMMEDIATE</policy>
      </changePolicyCase>
    </changePolicy>
    <changeAlignment>
      <changeAlignmentCase>
        <alignment>START_OF_BUNDLE</alignment>
      </changeAlignmentCase>
    </changeAlignment>
    <cancelPolicy>
      <cancelPolicyCase>
        <policy>IMMEDIATE</policy>
      </cancelPolicyCase>
    </cancelPolicy>
    <createAlignment>
      <createAlignmentCase>
        <alignment>START_OF_BUNDLE</alignment>
      </createAlignmentCase>
    </createAlignment>
    <billingAlignment>
      <billingAlignmentCase>
        <alignment>ACCOUNT</alignment>
      </billingAlignmentCase>
    </billingAlignment>
    <priceList>
      <priceListCase>
        <toPriceList>DEFAULT</toPriceList>
      </priceListCase>
    </priceList>
  </rules>
  <plans>
    <plan name="plan1">
      <product>product1</product>
      <initialPhases/>        
      <finalPhase type="FIXEDTERM">
        <duration>
          <unit>MONTHS</unit>
          <number>5</number>
        </duration>
        <fixed type="ONE_TIME">
          <fixedPrice>
            <price>
              <currency>USD</currency>
              <value>100.00</value>
            </price>
          </fixedPrice>
        </fixed>
        <recurring>
          <billingPeriod>DAILY</billingPeriod>
          <recurringPrice>
            <price>
              <currency>USD</currency>
              <value>50</value>
            </price>
          </recurringPrice>
        </recurring>
        <usages/>          
      </finalPhase>
      <plansAllowedInBundle>-1</plansAllowedInBundle>
    </plan>
	<plan name="plan2">
      <product>product2</product>
      <initialPhases/>        
      <finalPhase type="FIXEDTERM">
        <duration>
          <unit>MONTHS</unit>
          <number>5</number>
        </duration>
        <fixed type="ONE_TIME">
          <fixedPrice>
            <price>
              <currency>USD</currency>
              <value>150.00</value>
            </price>
          </fixedPrice>
        </fixed>
        <recurring>
          <billingPeriod>DAILY</billingPeriod>
          <recurringPrice>
            <price>
              <currency>USD</currency>
              <value>75</value>
            </price>
          </recurringPrice>
        </recurring>
        <usages/>
      </finalPhase>
      <plansAllowedInBundle>-1</plansAllowedInBundle>
    </plan>	
  </plans>
  <priceLists>
    <defaultPriceList name="DEFAULT">
      <plans>
        <plan>plan1</plan>
        <plan>plan2</plan>
      </plans>
    </defaultPriceList>
  </priceLists>
</catalog>`

**In this above catalog there are two plans available, I subscribe plan1 and do refunds applied in invoiceItem of itemType="fixedterm", refund API below**

POST: http://192.168.0.140:8080/killbill/1.0/kb/invoicePayments/{payment id}/refunds
header:  
X-Killbill-CreatedBy = admin
Content-Type = application/json
X-Killbill-ApiKey=apiKey
X-Killbill-ApiSecret=apiSecret
Authorization=Basic YWRtaW46cGFzc3dvcmQ=

Body:
{
  "amount": 5,
  "currency": "USD",
  "isAdjusted": true,
  "adjustments": [{
      "invoiceItemId": "invoice Item Id",
      "amount": 5,
      "currency": "USD"
    }]
}

**After, I do Subscription Upgrade from plan1 to plan2. API below,**

POST: http://192.168.0.140:8080/killbill/1.0/kb/subscriptions/{subscriptions id}
header:  
X-Killbill-CreatedBy = admin
Content-Type = application/json
X-Killbill-ApiKey=apiKey
X-Killbill-ApiSecret=apiSecret
Authorization=Basic YWRtaW46cGFzc3dvcmQ=

Body:
{
  "accountId": "{acount id}",
  "planName": "plan2"
}

**Subscription completed successfully, but invoices are not generated for upgrade. i found some error in console log find below,**

14:30:51.506 [bus_events-th] ?[34mINFO ?[0;39m ?[36mo.k.b.j.p.b.DefaultInternalBillingApi?[0;39m - Computed billing events for accountId='9ca6c55c-553
1-4566-8a95-7d195983a78d'
DefaultBillingEvent{type=CREATE, effectiveDate=2018-01-25T08:57:24.000Z, planPhaseName=plan1-fixedterm, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b5
56b6c, totalOrdering=1}
DefaultBillingEvent{type=CHANGE, effectiveDate=2018-01-25T09:00:50.000Z, planPhaseName=plan2-fixedterm, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b5
56b6c, totalOrdering=2}
14:30:51.519 [bus_events-th] ?[34mINFO ?[0;39m ?[36mo.k.b.i.g.FixedAndRecurringInvoiceItemGenerator?[0;39m - Proposed recurring items for invoiceId='e
7586a0b-bfde-43d7-b730-9d557c8f855e', accountId='9ca6c55c-5531-4566-8a95-7d195983a78d'
DefaultBillingEvent{type=CHANGE, effectiveDate=2018-01-25T09:00:50.000Z, planPhaseName=plan2-fixedterm, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b5
56b6c, totalOrdering=2}
        RECURRING{startDate=2018-01-25, endDate=2018-01-26, amount=75.00, rate=75, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b556b6c, linkedItemId=n
ull}
14:30:51.522 [bus_events-th] ?[34mINFO ?[0;39m ?[36mo.k.b.i.g.FixedAndRecurringInvoiceItemGenerator?[0;39m - Proposed fixed items for invoiceId='e7586
a0b-bfde-43d7-b730-9d557c8f855e', accountId='9ca6c55c-5531-4566-8a95-7d195983a78d'
DefaultBillingEvent{type=CREATE, effectiveDate=2018-01-25T08:57:24.000Z, planPhaseName=plan1-fixedterm, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b5
56b6c, totalOrdering=1}
        FIXED{startDate=2018-01-25, endDate=null, amount=100.00, rate=null, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b556b6c, linkedItemId=null}
DefaultBillingEvent{type=CHANGE, effectiveDate=2018-01-25T09:00:50.000Z, planPhaseName=plan2-fixedterm, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b5
56b6c, totalOrdering=2}
        FIXED{startDate=2018-01-25, endDate=null, amount=150.00, rate=null, subscriptionId=7c5cf673-2f15-4377-8f09-d6584b556b6c, linkedItemId=null}
14:30:51.527 [bus_events-th] ?[1;31mERROR?[0;39m ?[36mc.g.c.e.E.Killbill EventBus   ?[0;39m - Exception thrown by subscriber method handleSubscription
Transition(org.killbill.billing.events.EffectiveSubscriptionInternalEvent) on subscriber org.killbill.billing.invoice.InvoiceListener@ebcf7d when disp
atching event: DefaultEffectiveSubscriptionEvent{bundleId=83527c7a-84bb-4e8b-8759-de0f926cb9b8, totalOrdering=0, subscriptionId=7c5cf673-2f15-4377-8f0
9-d6584b556b6c, eventId=d95f5791-f766-4b01-b3e6-55f7d460ecee, requestedTransitionTime=2018-01-25T09:00:50.000Z, effectiveTransitionTime=2018-01-25T09:
00:50.000Z, previousState=ACTIVE, previousPriceList='DEFAULT', previousBillCycleDayLocal='null', previousPlan='plan1', previousPhase='plan1-fixedterm'
, nextState=ACTIVE, nextPriceList='DEFAULT', nextBillCycleDayLocal='null', nextPlan='plan2', nextPhase='plan2-fixedterm', remainingEventsForUserOperat
ion=0, transitionType=CHANGE, startDate=2018-01-25T08:57:24.000Z}
java.lang.NullPointerException: Unable to find item interval for id='168af01f-f04b-45ac-af9e-563ed0bca298', tree=ItemsNodeInterval{items=ItemsInterval
{items=[]}}
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1079)
        at org.killbill.billing.invoice.tree.ItemsNodeInterval.addAdjustment(ItemsNodeInterval.java:212)
        at org.killbill.billing.invoice.tree.SubscriptionItemTree.build(SubscriptionItemTree.java:127)
        at org.killbill.billing.invoice.tree.AccountItemTree.build(AccountItemTree.java:82)
        at org.killbill.billing.invoice.tree.AccountItemTree.mergeWithProposedItems(AccountItemTree.java:156)
        at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.generateItems(FixedAndRecurringInvoiceItemGenerator.java:112)
        at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:84)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:385)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:288)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:251)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountFromNotificationOrBusEvent(InvoiceDispatcher.java:228)
        at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:210)
        at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:185)
        at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:181)
        at org.killbill.billing.invoice.InvoiceListener.handleSubscriptionTransition(InvoiceListener.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$ImmediateDispatcher.dispatch(Dispatcher.java:200)
        at com.google.common.eventbus.EventBusThatThrowsException.postWithException(EventBusThatThrowsException.java:65)
        at org.killbill.bus.DefaultPersistentBus.dispatchBusEventWithMetrics(DefaultPersistentBus.java:314)
        at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:40)
        at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:29)
        at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
        at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
        at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
14:30:51.569 [bus_events-th] ?[1;31mERROR?[0;39m ?[36mo.k.q.d.CallableCallbackBase  ?[0;39m - Fatal NotificationQ dispatch error, data corruption...
com.google.common.eventbus.EventBusException: java.lang.reflect.InvocationTargetException
        at com.google.common.eventbus.EventBusThatThrowsException.postWithException(EventBusThatThrowsException.java:78)
        at org.killbill.bus.DefaultPersistentBus.dispatchBusEventWithMetrics(DefaultPersistentBus.java:314)
        at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:40)
        at org.killbill.bus.dispatching.BusCallableCallback.dispatch(BusCallableCallback.java:29)
        at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:103)
        at org.killbill.queue.dispatching.Dispatcher$CallableQueue.call(Dispatcher.java:86)
        at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
        at com.google.common.eventbus.EventBusThatThrowsException$SubscriberExceptionsTrackerHandler.handleException(EventBusThatThrowsException.java:
129)
        at com.google.common.eventbus.EventBus.handleSubscriberException(EventBus.java:175)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:78)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$ImmediateDispatcher.dispatch(Dispatcher.java:200)
        at com.google.common.eventbus.EventBusThatThrowsException.postWithException(EventBusThatThrowsException.java:65)
        ... 11 common frames omitted
Caused by: java.lang.NullPointerException: Unable to find item interval for id='168af01f-f04b-45ac-af9e-563ed0bca298', tree=ItemsNodeInterval{items=It
emsInterval{items=[]}}
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1079)
        at org.killbill.billing.invoice.tree.ItemsNodeInterval.addAdjustment(ItemsNodeInterval.java:212)
        at org.killbill.billing.invoice.tree.SubscriptionItemTree.build(SubscriptionItemTree.java:127)
        at org.killbill.billing.invoice.tree.AccountItemTree.build(AccountItemTree.java:82)
        at org.killbill.billing.invoice.tree.AccountItemTree.mergeWithProposedItems(AccountItemTree.java:156)
        at org.killbill.billing.invoice.generator.FixedAndRecurringInvoiceItemGenerator.generateItems(FixedAndRecurringInvoiceItemGenerator.java:112)
        at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:84)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:385)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:288)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:251)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountFromNotificationOrBusEvent(InvoiceDispatcher.java:228)
        at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionInternal(InvoiceDispatcher.java:210)
        at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:185)
        at org.killbill.billing.invoice.InvoiceDispatcher.processSubscriptionForInvoiceGeneration(InvoiceDispatcher.java:181)
        at org.killbill.billing.invoice.InvoiceListener.handleSubscriptionTransition(InvoiceListener.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        ... 15 common frames omitted

**How to overcome this problem ?**

**Comment by sbrossie** [comment]
@Arulraj12 Please use the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) for questions and follow the [guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md#how-to-contribute-to-kill-bill) before you open new GH issues.
