### ISSUE TITLE
Getting "Double billing detected:.." when changing the billing amount from 0$ to 3$ on the same day

### ISSUE THREAD

**Issue by legokangpalla** [killbill/killbill#877]
I think this issue was discussed here: https://github.com/killbill/killbill/issues/783
I changed the billing plan from a 0$ plan to 3$ plan on the same day and I am getting the error message

`Double billing detected: [Item{id=3a185150-7f28-4123-868d-1985436aa4a8, accountId=ed91bdb4-8136-4c60-9d22-256be3960fb9, bundleId=f62eb65b-842d-4833-b372-7a36d7431bf0, subscriptionId=079e2a55-ff3d-4920-aac4-8d65e70818b2, targetInvoiceId=142a3917-24f6-41ae-8998-42041bd43c94, invoiceId=9673bb0f-d64f-4f64-b55c-84d625ba4ae6, planName='PRD_0000000006_PL_000001', phaseName='PRD_0000000006_PL_000001-evergreen', startDate=2018-02-26, endDate=2018-03-26, amount=0, rate=0E-9, currency=KRW, createdDate=2018-02-26T09:51:11.000Z, linkedId=null, currentRepairedAmount=0, adjustedAmount=0, action=ADD}, Item{id=90e36cc9-1e60-4ad3-a807-fa7c40fdf690, accountId=ed91bdb4-8136-4c60-9d22-256be3960fb9, bundleId=f62eb65b-842d-4833-b372-7a36d7431bf0, subscriptionId=079e2a55-ff3d-4920-aac4-8d65e70818b2, targetInvoiceId=142a3917-24f6-41ae-8998-42041bd43c94, invoiceId=fdb96c34-e32a-406b-9bfe-e7307f1df1fc, planName='PRD_0000000007_PL_000001', phaseName='PRD_0000000007_PL_000001-evergreen', startDate=2018-02-26, endDate=2018-03-26, amount=30000, rate=30000.000000000, currency=KRW, createdDate=2018-02-26T09:51:29.000Z, linkedId=null, currentRepairedAmount=0, adjustedAmount=0, action=ADD}]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.killbill.billing.invoice.tree.ItemsInterval.getResulting_ADD_Item(ItemsInterval.java:222)
	at org.killbill.billing.invoice.tree.ItemsInterval.getResultingItem(ItemsInterval.java:197)
	at org.killbill.billing.invoice.tree.ItemsInterval.createNewItem(ItemsInterval.java:180)
	at org.killbill.billing.invoice.tree.ItemsInterval.buildForMissingInterval(ItemsInterval.java:153)
	at org.killbill.billing.invoice.tree.ItemsInterval.buildFromItems(ItemsInterval.java:161)
`

**Comment by sbrossie** [comment]
@legokangpalla Could you please use the [mailing list](https://groups.google.com/forum/#!forum/killbilling-users) instead of filing issues?

Also which version are you using?

**Comment by pierre** [comment]
Closing for lack of activity.
