### ISSUE TITLE
NullPointerException on POST on /invoices

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill#936]
Trying to make a POST request on the /invoices API of KillBill 0.18.11 generates a NullPointerException with the same stack trace as described in this mail on the list:
https://groups.google.com/d/msg/killbilling-users/8b2SQw7WRto/9HjWqagRBwAJ

```
java.lang.NullPointerException: null 
        at org.killbill.billing.invoice.usage.ContiguousIntervalUsageInArrear.getRolledUpUsage(ContiguousIntervalUsageInArrear.java:267) 
        at org.killbill.billing.invoice.usage.ContiguousIntervalUsageInArrear.computeMissingItemsAndNextNotificationDate(ContiguousIntervalUsageInArrear.java:184) 
        at org.killbill.billing.invoice.usage.SubscriptionUsageInArrear.computeMissingUsageInvoiceItems(SubscriptionUsageInArrear.java:115) 
        at org.killbill.billing.invoice.generator.UsageInvoiceItemGenerator.generateItems(UsageInvoiceItemGenerator.java:121) 
        at org.killbill.billing.invoice.generator.DefaultInvoiceGenerator.generateInvoice(DefaultInvoiceGenerator.java:97) 
        at org.killbill.billing.invoice.InvoiceDispatcher.generateKillBillInvoice(InvoiceDispatcher.java:633) 
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:519) 
        at org.killbill.billing.invoice.InvoiceDispatcher.processDryRun_TARGET_DATE_Invoice(InvoiceDispatcher.java:468) 
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:380) 
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:299) 
        at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerInvoiceGeneration(DefaultInvoiceUserApi.java:231) 
        at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52) 
        at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33) 
        at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49) 
        at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45) 
        at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68) 
        at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32) 
        at org.killbill.billing.jaxrs.resources.InvoiceResource.generateDryRunInvoice(InvoiceResource.java:398) 
        at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69) 
        at sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:498) 
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) 
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) 
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) 
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) 
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) 
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) 
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) 
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) 
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) 
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) 
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) 
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) 
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) 
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) 
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) 
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) 
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) 
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) 
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) 
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) 
        at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:110) 
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) 
        at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75) 
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) 
        at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49) 
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) 
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) 
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44) 
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) 
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) 
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41) 
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) 
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) 
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) 
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) 
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) 
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) 
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) 
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) 
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) 
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) 
        at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:279) 
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) 
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) 
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) 
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) 
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) 
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) 
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
        at java.lang.Thread.run(Thread.java:748) 
```

In the list, there seem to be an indication that a fix has been made with commit https://github.com/killbill/killbill/commit/00224172730e7638300f1e15112dd7cca1c41a76 on KillBill 0.19. I'm adding this issue because having had this with 0.18, a fix should probably be ported to that version too.

**Comment by sbrossie** [comment]
@GregOriol We could backport that fix to `0.18.x` branches, however we need to make sure this works and address the use you reported. If you were interested to try it out, and submit PR against `0.18.x`, we would merge it.

**Comment by GregOriol** [comment]
@sbrossie Actually I don't use the feature or need the patch: I just stumbled into this NPE by mistake while trying some APIs :-) I added the issue so that it is logged and known, if someone else gets this error, or if someone wants to port the patch. In fact, I don't even know the scenario to produce this npe, I definitely was doing something normal, maybe it was something related to a config in my catalog, I found out I was looking for another API in the end, so I didn't investigate this issue any further.

**Comment by sbrossie** [comment]
Closing, as this is fixed in current dev branch, and we hope to release that soon.
